<a href="https://colab.research.google.com/github/DoItSon/playdata/blob/main/Python2/04_pymysql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [127]:
!pip install pymysql

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pymysql in /usr/local/lib/python3.7/dist-packages (1.0.2)

- 구글 드라이브 연결

In [128]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [129]:
import yaml
DB_INFO = "/content/drive/MyDrive/data/db.yaml"
with open(DB_INFO,"r") as f:
    db_info = yaml.load(f, Loader=yaml.Loader)

- DB 접속정보

In [ ]:
db_info

In [132]:
HOST = db_info["HOST"]
USER = db_info["USER"]
PASSWD = db_info["PASSWD"]
PORT = 3306

- connect 함수를 이용하여 연결객체 받아오기

In [133]:
import pymysql
conn = pymysql.connect(
    user = USER,
    passwd = PASSWD,
    host = HOST,
    port = PORT,
    db = 'playdata'
)
conn

- Cursor 객체
    - sql 구문을 실행하기 위한 객체

In [134]:
cursor = conn.cursor()
cursor

- execute 메소드를 이용하여 서버에 sql전송하기

In [135]:
sql = "select * from titanic_raw;"
cursor.execute(sql)

1309

In [136]:
result = cursor.fetchall() # 쿼리에 실행결과를 다 가져오는 메소드 (한번 실행하면 사라진다.)
result[:2]

((1,
  0,
  3,
  'Braund, Mr. Owen Harris',
  'male',
  22.0,
  1,
  0,
  'A/5 21171',
  7.25,
  None,
  'S'),
 (2,
  1,
  1,
  'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'female',
  38.0,
  1,
  0,
  'PC 17599',
  71.2833,
  'C85',
  'C'))

- dict 형식으로 쿼리 실행결과 받아오기

In [137]:
cursor = conn.cursor(pymysql.cursors.DictCursor)
cursor

In [138]:
sql = "select * from titanic_raw;"
cursor.execute(sql)

1309

In [139]:
result = cursor.fetchall() # 쿼리에 실행결과를 다 가져오는 메소드 (한번 실행하면 사라진다.)
result[:2]

[{'passengerid': 1,
  'survived': 0,
  'pclass': 3,
  'name': 'Braund, Mr. Owen Harris',
  'gender': 'male',
  'age': 22.0,
  'sibsp': 1,
  'parch': 0,
  'ticket': 'A/5 21171',
  'fare': 7.25,
  'cabin': None,
  'embarked': 'S'},
 {'passengerid': 2,
  'survived': 1,
  'pclass': 1,
  'name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
  'gender': 'female',
  'age': 38.0,
  'sibsp': 1,
  'parch': 0,
  'ticket': 'PC 17599',
  'fare': 71.2833,
  'cabin': 'C85',
  'embarked': 'C'}]

In [140]:
cursor.execute(sql)
for row in cursor.fetchall():
    print(row)

{'passengerid': 1, 'survived': 0, 'pclass': 3, 'name': 'Braund, Mr. Owen Harris', 'gender': 'male', 'age': 22.0, 'sibsp': 1, 'parch': 0, 'ticket': 'A/5 21171', 'fare': 7.25, 'cabin': None, 'embarked': 'S'}
{'passengerid': 2, 'survived': 1, 'pclass': 1, 'name': 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'gender': 'female', 'age': 38.0, 'sibsp': 1, 'parch': 0, 'ticket': 'PC 17599', 'fare': 71.2833, 'cabin': 'C85', 'embarked': 'C'}
{'passengerid': 3, 'survived': 1, 'pclass': 3, 'name': 'Heikkinen, Miss. Laina', 'gender': 'female', 'age': 26.0, 'sibsp': 0, 'parch': 0, 'ticket': 'STON/O2. 3101282', 'fare': 7.925, 'cabin': None, 'embarked': 'S'}
{'passengerid': 4, 'survived': 1, 'pclass': 1, 'name': 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'gender': 'female', 'age': 35.0, 'sibsp': 1, 'parch': 0, 'ticket': '113803', 'fare': 53.1, 'cabin': 'C123', 'embarked': 'S'}
{'passengerid': 5, 'survived': 0, 'pclass': 3, 'name': 'Allen, Mr. William Henry', 'gender': 'male', 'age': 35.0, 'sibsp': 0, 'parch': 0, 'ticket': '373450', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 6, 'survived': 0, 'pclass': 3, 'name': 'Moran, Mr. James', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '330877', 'fare': 8.4583, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 7, 'survived': 0, 'pclass': 1, 'name': 'McCarthy, Mr. Timothy J', 'gender': 'male', 'age': 54.0, 'sibsp': 0, 'parch': 0, 'ticket': '17463', 'fare': 51.8625, 'cabin': 'E46', 'embarked': 'S'}
{'passengerid': 8, 'survived': 0, 'pclass': 3, 'name': 'Palsson, Master. Gosta Leonard', 'gender': 'male', 'age': 2.0, 'sibsp': 3, 'parch': 1, 'ticket': '349909', 'fare': 21.075, 'cabin': None, 'embarked': 'S'}
{'passengerid': 9, 'survived': 1, 'pclass': 3, 'name': 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)', 'gender': 'female', 'age': 27.0, 'sibsp': 0, 'parch': 2, 'ticket': '347742', 'fare': 11.1333, 'cabin': None, 'embarked': 'S'}
{'passengerid': 10, 'survived': 1, 'pclass': 2, 'name': 'Nasser, Mrs. Nicholas (Adele Achem)', 'gender': 'female', 'age': 14.0, 'sibsp': 1, 'parch': 0, 'ticket': '237736', 'fare': 30.0708, 'cabin': None, 'embarked': 'C'}
{'passengerid': 11, 'survived': 1, 'pclass': 3, 'name': 'Sandstrom, Miss. Marguerite Rut', 'gender': 'female', 'age': 4.0, 'sibsp': 1, 'parch': 1, 'ticket': 'PP 9549', 'fare': 16.7, 'cabin': 'G6', 'embarked': 'S'}
{'passengerid': 12, 'survived': 1, 'pclass': 1, 'name': 'Bonnell, Miss. Elizabeth', 'gender': 'female', 'age': 58.0, 'sibsp': 0, 'parch': 0, 'ticket': '113783', 'fare': 26.55, 'cabin': 'C103', 'embarked': 'S'}
{'passengerid': 13, 'survived': 0, 'pclass': 3, 'name': 'Saundercock, Mr. William Henry', 'gender': 'male', 'age': 20.0, 'sibsp': 0, 'parch': 0, 'ticket': 'A/5. 2151', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 14, 'survived': 0, 'pclass': 3, 'name': 'Andersson, Mr. Anders Johan', 'gender': 'male', 'age': 39.0, 'sibsp': 1, 'parch': 5, 'ticket': '347082', 'fare': 31.275, 'cabin': None, 'embarked': 'S'}
{'passengerid': 15, 'survived': 0, 'pclass': 3, 'name': 'Vestrom, Miss. Hulda Amanda Adolfina', 'gender': 'female', 'age': 14.0, 'sibsp': 0, 'parch': 0, 'ticket': '350406', 'fare': 7.8542, 'cabin': None, 'embarked': 'S'}
{'passengerid': 16, 'survived': 1, 'pclass': 2, 'name': 'Hewlett, Mrs. (Mary D Kingcome) ', 'gender': 'female', 'age': 55.0, 'sibsp': 0, 'parch': 0, 'ticket': '248706', 'fare': 16.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 17, 'survived': 0, 'pclass': 3, 'name': 'Rice, Master. Eugene', 'gender': 'male', 'age': 2.0, 'sibsp': 4, 'parch': 1, 'ticket': '382652', 'fare': 29.125, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 18, 'survived': 1, 'pclass': 2, 'name': 'Williams, Mr. Charles Eugene', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '244373', 'fare': 13.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 19, 'survived': 0, 'pclass': 3, 'name': 'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)', 'gender': 'female', 'age': 31.0, 'sibsp': 1, 'parch': 0, 'ticket': '345763', 'fare': 18.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 20, 'survived': 1, 'pclass': 3, 'name': 'Masselmani, Mrs. Fatima', 'gender': 'female', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '2649', 'fare': 7.225, 'cabin': None, 'embarked': 'C'}
{'passengerid': 21, 'survived': 0, 'pclass': 2, 'name': 'Fynney, Mr. Joseph J', 'gender': 'male', 'age': 35.0, 'sibsp': 0, 'parch': 0, 'ticket': '239865', 'fare': 26.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 22, 'survived': 1, 'pclass': 2, 'name': 'Beesley, Mr. Lawrence', 'gender': 'male', 'age': 34.0, 'sibsp': 0, 'parch': 0, 'ticket': '248698', 'fare': 13.0, 'cabin': 'D56', 'embarked': 'S'}
{'passengerid': 23, 'survived': 1, 'pclass': 3, 'name': 'McGowan, Miss. Anna "Annie"', 'gender': 'female', 'age': 15.0, 'sibsp': 0, 'parch': 0, 'ticket': '330923', 'fare': 8.0292, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 24, 'survived': 1, 'pclass': 1, 'name': 'Sloper, Mr. William Thompson', 'gender': 'male', 'age': 28.0, 'sibsp': 0, 'parch': 0, 'ticket': '113788', 'fare': 35.5, 'cabin': 'A6', 'embarked': 'S'}
{'passengerid': 25, 'survived': 0, 'pclass': 3, 'name': 'Palsson, Miss. Torborg Danira', 'gender': 'female', 'age': 8.0, 'sibsp': 3, 'parch': 1, 'ticket': '349909', 'fare': 21.075, 'cabin': None, 'embarked': 'S'}
{'passengerid': 26, 'survived': 1, 'pclass': 3, 'name': 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)', 'gender': 'female', 'age': 38.0, 'sibsp': 1, 'parch': 5, 'ticket': '347077', 'fare': 31.3875, 'cabin': None, 'embarked': 'S'}
{'passengerid': 27, 'survived': 0, 'pclass': 3, 'name': 'Emir, Mr. Farred Chehab', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '2631', 'fare': 7.225, 'cabin': None, 'embarked': 'C'}
{'passengerid': 28, 'survived': 0, 'pclass': 1, 'name': 'Fortune, Mr. Charles Alexander', 'gender': 'male', 'age': 19.0, 'sibsp': 3, 'parch': 2, 'ticket': '19950', 'fare': 263.0, 'cabin': 'C23 C25 C27', 'embarked': 'S'}
{'passengerid': 29, 'survived': 1, 'pclass': 3, 'name': 'O\'Dwyer, Miss. Ellen "Nellie"', 'gender': 'female', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '330959', 'fare': 7.8792, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 30, 'survived': 0, 'pclass': 3, 'name': 'Todoroff, Mr. Lalio', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '349216', 'fare': 7.8958, 'cabin': None, 'embarked': 'S'}
{'passengerid': 31, 'survived': 0, 'pclass': 1, 'name': 'Uruchurtu, Don. Manuel E', 'gender': 'male', 'age': 40.0, 'sibsp': 0, 'parch': 0, 'ticket': 'PC 17601', 'fare': 27.7208, 'cabin': None, 'embarked': 'C'}
{'passengerid': 32, 'survived': 1, 'pclass': 1, 'name': 'Spencer, Mrs. William Augustus (Marie Eugenie)', 'gender': 'female', 'age': None, 'sibsp': 1, 'parch': 0, 'ticket': 'PC 17569', 'fare': 146.5208, 'cabin': 'B78', 'embarked': 'C'}
{'passengerid': 33, 'survived': 1, 'pclass': 3, 'name': 'Glynn, Miss. Mary Agatha', 'gender': 'female', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '335677', 'fare': 7.75, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 34, 'survived': 0, 'pclass': 2, 'name': 'Wheadon, Mr. Edward H', 'gender': 'male', 'age': 66.0, 'sibsp': 0, 'parch': 0, 'ticket': 'C.A. 24579', 'fare': 10.5, 'cabin': None, 'embarked': 'S'}
{'passengerid': 35, 'survived': 0, 'pclass': 1, 'name': 'Meyer, Mr. Edgar Joseph', 'gender': 'male', 'age': 28.0, 'sibsp': 1, 'parch': 0, 'ticket': 'PC 17604', 'fare': 82.1708, 'cabin': None, 'embarked': 'C'}
{'passengerid': 36, 'survived': 0, 'pclass': 1, 'name': 'Holverson, Mr. Alexander Oskar', 'gender': 'male', 'age': 42.0, 'sibsp': 1, 'parch': 0, 'ticket': '113789', 'fare': 52.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 37, 'survived': 1, 'pclass': 3, 'name': 'Mamee, Mr. Hanna', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '2677', 'fare': 7.2292, 'cabin': None, 'embarked': 'C'}
{'passengerid': 38, 'survived': 0, 'pclass': 3, 'name': 'Cann, Mr. Ernest Charles', 'gender': 'male', 'age': 21.0, 'sibsp': 0, 'parch': 0, 'ticket': 'A./5. 2152', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 39, 'survived': 0, 'pclass': 3, 'name': 'Vander Planke, Miss. Augusta Maria', 'gender': 'female', 'age': 18.0, 'sibsp': 2, 'parch': 0, 'ticket': '345764', 'fare': 18.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 40, 'survived': 1, 'pclass': 3, 'name': 'Nicola-Yarred, Miss. Jamila', 'gender': 'female', 'age': 14.0, 'sibsp': 1, 'parch': 0, 'ticket': '2651', 'fare': 11.2417, 'cabin': None, 'embarked': 'C'}
{'passengerid': 41, 'survived': 0, 'pclass': 3, 'name': 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)', 'gender': 'female', 'age': 40.0, 'sibsp': 1, 'parch': 0, 'ticket': '7546', 'fare': 9.475, 'cabin': None, 'embarked': 'S'}
{'passengerid': 42, 'survived': 0, 'pclass': 2, 'name': 'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)', 'gender': 'female', 'age': 27.0, 'sibsp': 1, 'parch': 0, 'ticket': '11668', 'fare': 21.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 43, 'survived': 0, 'pclass': 3, 'name': 'Kraeff, Mr. Theodor', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '349253', 'fare': 7.8958, 'cabin': None, 'embarked': 'C'}
{'passengerid': 44, 'survived': 1, 'pclass': 2, 'name': 'Laroche, Miss. Simonne Marie Anne Andree', 'gender': 'female', 'age': 3.0, 'sibsp': 1, 'parch': 2, 'ticket': 'SC/Paris 2123', 'fare': 41.5792, 'cabin': None, 'embarked': 'C'}
{'passengerid': 45, 'survived': 1, 'pclass': 3, 'name': 'Devaney, Miss. Margaret Delia', 'gender': 'female', 'age': 19.0, 'sibsp': 0, 'parch': 0, 'ticket': '330958', 'fare': 7.8792, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 46, 'survived': 0, 'pclass': 3, 'name': 'Rogers, Mr. William John', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': 'S.C./A.4. 23567', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 47, 'survived': 0, 'pclass': 3, 'name': 'Lennon, Mr. Denis', 'gender': 'male', 'age': None, 'sibsp': 1, 'parch': 0, 'ticket': '370371', 'fare': 15.5, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 48, 'survived': 1, 'pclass': 3, 'name': "O'Driscoll, Miss. Bridget", 'gender': 'female', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '14311', 'fare': 7.75, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 49, 'survived': 0, 'pclass': 3, 'name': 'Samaan, Mr. Youssef', 'gender': 'male', 'age': None, 'sibsp': 2, 'parch': 0, 'ticket': '2662', 'fare': 21.6792, 'cabin': None, 'embarked': 'C'}
{'passengerid': 50, 'survived': 0, 'pclass': 3, 'name': 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)', 'gender': 'female', 'age': 18.0, 'sibsp': 1, 'parch': 0, 'ticket': '349237', 'fare': 17.8, 'cabin': None, 'embarked': 'S'}
{'passengerid': 51, 'survived': 0, 'pclass': 3, 'name': 'Panula, Master. Juha Niilo', 'gender': 'male', 'age': 7.0, 'sibsp': 4, 'parch': 1, 'ticket': '3101295', 'fare': 39.6875, 'cabin': None, 'embarked': 'S'}
{'passengerid': 52, 'survived': 0, 'pclass': 3, 'name': 'Nosworthy, Mr. Richard Cater', 'gender': 'male', 'age': 21.0, 'sibsp': 0, 'parch': 0, 'ticket': 'A/4. 39886', 'fare': 7.8, 'cabin': None, 'embarked': 'S'}
{'passengerid': 53, 'survived': 1, 'pclass': 1, 'name': 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'gender': 'female', 'age': 49.0, 'sibsp': 1, 'parch': 0, 'ticket': 'PC 17572', 'fare': 76.7292, 'cabin': 'D33', 'embarked': 'C'}
{'passengerid': 54, 'survived': 1, 'pclass': 2, 'name': 'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)', 'gender': 'female', 'age': 29.0, 'sibsp': 1, 'parch': 0, 'ticket': '2926', 'fare': 26.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 55, 'survived': 0, 'pclass': 1, 'name': 'Ostby, Mr. Engelhart Cornelius', 'gender': 'male', 'age': 65.0, 'sibsp': 0, 'parch': 1, 'ticket': '113509', 'fare': 61.9792, 'cabin': 'B30', 'embarked': 'C'}
{'passengerid': 56, 'survived': 1, 'pclass': 1, 'name': 'Woolner, Mr. Hugh', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '19947', 'fare': 35.5, 'cabin': 'C52', 'embarked': 'S'}
{'passengerid': 57, 'survived': 1, 'pclass': 2, 'name': 'Rugg, Miss. Emily', 'gender': 'female', 'age': 21.0, 'sibsp': 0, 'parch': 0, 'ticket': 'C.A. 31026', 'fare': 10.5, 'cabin': None, 'embarked': 'S'}
{'passengerid': 58, 'survived': 0, 'pclass': 3, 'name': 'Novel, Mr. Mansouer', 'gender': 'male', 'age': 28.5, 'sibsp': 0, 'parch': 0, 'ticket': '2697', 'fare': 7.2292, 'cabin': None, 'embarked': 'C'}
{'passengerid': 59, 'survived': 1, 'pclass': 2, 'name': 'West, Miss. Constance Mirium', 'gender': 'female', 'age': 5.0, 'sibsp': 1, 'parch': 2, 'ticket': 'C.A. 34651', 'fare': 27.75, 'cabin': None, 'embarked': 'S'}
{'passengerid': 60, 'survived': 0, 'pclass': 3, 'name': 'Goodwin, Master. William Frederick', 'gender': 'male', 'age': 11.0, 'sibsp': 5, 'parch': 2, 'ticket': 'CA 2144', 'fare': 46.9, 'cabin': None, 'embarked': 'S'}
{'passengerid': 61, 'survived': 0, 'pclass': 3, 'name': 'Sirayanian, Mr. Orsen', 'gender': 'male', 'age': 22.0, 'sibsp': 0, 'parch': 0, 'ticket': '2669', 'fare': 7.2292, 'cabin': None, 'embarked': 'C'}
{'passengerid': 62, 'survived': 1, 'pclass': 1, 'name': 'Icard, Miss. Amelie', 'gender': 'female', 'age': 38.0, 'sibsp': 0, 'parch': 0, 'ticket': '113572', 'fare': 80.0, 'cabin': 'B28', 'embarked': None}
{'passengerid': 63, 'survived': 0, 'pclass': 1, 'name': 'Harris, Mr. Henry Birkhardt', 'gender': 'male', 'age': 45.0, 'sibsp': 1, 'parch': 0, 'ticket': '36973', 'fare': 83.475, 'cabin': 'C83', 'embarked': 'S'}
{'passengerid': 64, 'survived': 0, 'pclass': 3, 'name': 'Skoog, Master. Harald', 'gender': 'male', 'age': 4.0, 'sibsp': 3, 'parch': 2, 'ticket': '347088', 'fare': 27.9, 'cabin': None, 'embarked': 'S'}
{'passengerid': 65, 'survived': 0, 'pclass': 1, 'name': 'Stewart, Mr. Albert A', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': 'PC 17605', 'fare': 27.7208, 'cabin': None, 'embarked': 'C'}
{'passengerid': 66, 'survived': 1, 'pclass': 3, 'name': 'Moubarek, Master. Gerios', 'gender': 'male', 'age': None, 'sibsp': 1, 'parch': 1, 'ticket': '2661', 'fare': 15.2458, 'cabin': None, 'embarked': 'C'}
{'passengerid': 67, 'survived': 1, 'pclass': 2, 'name': 'Nye, Mrs. (Elizabeth Ramell)', 'gender': 'female', 'age': 29.0, 'sibsp': 0, 'parch': 0, 'ticket': 'C.A. 29395', 'fare': 10.5, 'cabin': 'F33', 'embarked': 'S'}
{'passengerid': 68, 'survived': 0, 'pclass': 3, 'name': 'Crease, Mr. Ernest James', 'gender': 'male', 'age': 19.0, 'sibsp': 0, 'parch': 0, 'ticket': 'S.P. 3464', 'fare': 8.1583, 'cabin': None, 'embarked': 'S'}
{'passengerid': 69, 'survived': 1, 'pclass': 3, 'name': 'Andersson, Miss. Erna Alexandra', 'gender': 'female', 'age': 17.0, 'sibsp': 4, 'parch': 2, 'ticket': '3101281', 'fare': 7.925, 'cabin': None, 'embarked': 'S'}
{'passengerid': 70, 'survived': 0, 'pclass': 3, 'name': 'Kink, Mr. Vincenz', 'gender': 'male', 'age': 26.0, 'sibsp': 2, 'parch': 0, 'ticket': '315151', 'fare': 8.6625, 'cabin': None, 'embarked': 'S'}
{'passengerid': 71, 'survived': 0, 'pclass': 2, 'name': 'Jenkin, Mr. Stephen Curnow', 'gender': 'male', 'age': 32.0, 'sibsp': 0, 'parch': 0, 'ticket': 'C.A. 33111', 'fare': 10.5, 'cabin': None, 'embarked': 'S'}
{'passengerid': 72, 'survived': 0, 'pclass': 3, 'name': 'Goodwin, Miss. Lillian Amy', 'gender': 'female', 'age': 16.0, 'sibsp': 5, 'parch': 2, 'ticket': 'CA 2144', 'fare': 46.9, 'cabin': None, 'embarked': 'S'}
{'passengerid': 73, 'survived': 0, 'pclass': 2, 'name': 'Hood, Mr. Ambrose Jr', 'gender': 'male', 'age': 21.0, 'sibsp': 0, 'parch': 0, 'ticket': 'S.O.C. 14879', 'fare': 73.5, 'cabin': None, 'embarked': 'S'}
{'passengerid': 74, 'survived': 0, 'pclass': 3, 'name': 'Chronopoulos, Mr. Apostolos', 'gender': 'male', 'age': 26.0, 'sibsp': 1, 'parch': 0, 'ticket': '2680', 'fare': 14.4542, 'cabin': None, 'embarked': 'C'}
{'passengerid': 75, 'survived': 1, 'pclass': 3, 'name': 'Bing, Mr. Lee', 'gender': 'male', 'age': 32.0, 'sibsp': 0, 'parch': 0, 'ticket': '1601', 'fare': 56.4958, 'cabin': None, 'embarked': 'S'}
{'passengerid': 76, 'survived': 0, 'pclass': 3, 'name': 'Moen, Mr. Sigurd Hansen', 'gender': 'male', 'age': 25.0, 'sibsp': 0, 'parch': 0, 'ticket': '348123', 'fare': 7.65, 'cabin': 'F G73', 'embarked': 'S'}
{'passengerid': 77, 'survived': 0, 'pclass': 3, 'name': 'Staneff, Mr. Ivan', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '349208', 'fare': 7.8958, 'cabin': None, 'embarked': 'S'}
{'passengerid': 78, 'survived': 0, 'pclass': 3, 'name': 'Moutal, Mr. Rahamin Haim', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '374746', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 79, 'survived': 1, 'pclass': 2, 'name': 'Caldwell, Master. Alden Gates', 'gender': 'male', 'age': 0.83, 'sibsp': 0, 'parch': 2, 'ticket': '248738', 'fare': 29.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 80, 'survived': 1, 'pclass': 3, 'name': 'Dowdell, Miss. Elizabeth', 'gender': 'female', 'age': 30.0, 'sibsp': 0, 'parch': 0, 'ticket': '364516', 'fare': 12.475, 'cabin': None, 'embarked': 'S'}
{'passengerid': 81, 'survived': 0, 'pclass': 3, 'name': 'Waelens, Mr. Achille', 'gender': 'male', 'age': 22.0, 'sibsp': 0, 'parch': 0, 'ticket': '345767', 'fare': 9.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 82, 'survived': 1, 'pclass': 3, 'name': 'Sheerlinck, Mr. Jan Baptist', 'gender': 'male', 'age': 29.0, 'sibsp': 0, 'parch': 0, 'ticket': '345779', 'fare': 9.5, 'cabin': None, 'embarked': 'S'}
{'passengerid': 83, 'survived': 1, 'pclass': 3, 'name': 'McDermott, Miss. Brigdet Delia', 'gender': 'female', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': '330932', 'fare': 7.7875, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 84, 'survived': 0, 'pclass': 1, 'name': 'Carrau, Mr. Francisco M', 'gender': 'male', 'age': 28.0, 'sibsp': 0, 'parch': 0, 'ticket': '113059', 'fare': 47.1, 'cabin': None, 'embarked': 'S'}
{'passengerid': 85, 'survived': 1, 'pclass': 2, 'name': 'Ilett, Miss. Bertha', 'gender': 'female', 'age': 17.0, 'sibsp': 0, 'parch': 0, 'ticket': 'SO/C 14885', 'fare': 10.5, 'cabin': None, 'embarked': 'S'}
{'passengerid': 86, 'survived': 1, 'pclass': 3, 'name': 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)', 'gender': 'female', 'age': 33.0, 'sibsp': 3, 'parch': 0, 'ticket': '3101278', 'fare': 15.85, 'cabin': None, 'embarked': 'S'}
{'passengerid': 87, 'survived': 0, 'pclass': 3, 'name': 'Ford, Mr. William Neal', 'gender': 'male', 'age': 16.0, 'sibsp': 1, 'parch': 3, 'ticket': 'W./C. 6608', 'fare': 34.375, 'cabin': None, 'embarked': 'S'}
{'passengerid': 88, 'survived': 0, 'pclass': 3, 'name': 'Slocovski, Mr. Selman Francis', 'gender': 'male', 'age': None, 'sibsp': 0, 'parch': 0, 'ticket': 'SOTON/OQ 392086', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 89, 'survived': 1, 'pclass': 1, 'name': 'Fortune, Miss. Mabel Helen', 'gender': 'female', 'age': 23.0, 'sibsp': 3, 'parch': 2, 'ticket': '19950', 'fare': 263.0, 'cabin': 'C23 C25 C27', 'embarked': 'S'}
{'passengerid': 90, 'survived': 0, 'pclass': 3, 'name': 'Celotti, Mr. Francesco', 'gender': 'male', 'age': 24.0, 'sibsp': 0, 'parch': 0, 'ticket': '343275', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 91, 'survived': 0, 'pclass': 3, 'name': 'Christmann, Mr. Emil', 'gender': 'male', 'age': 29.0, 'sibsp': 0, 'parch': 0, 'ticket': '343276', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 92, 'survived': 0, 'pclass': 3, 'name': 'Andreasson, Mr. Paul Edvin', 'gender': 'male', 'age': 20.0, 'sibsp': 0, 'parch': 0, 'ticket': '347466', 'fare': 7.8542, 'cabin': None, 'embarked': 'S'}
{'passengerid': 93, 'survived': 0, 'pclass': 1, 'name': 'Chaffee, Mr. Herbert Fuller', 'gender': 'male', 'age': 46.0, 'sibsp': 1, 'parch': 0, 'ticket': 'W.E.P. 5734', 'fare': 61.175, 'cabin': 'E31', 'embarked': 'S'}
{'passengerid': 94, 'survived': 0, 'pclass': 3, 'name': 'Dean, Mr. Bertram Frank', 'gender': 'male', 'age': 26.0, 'sibsp': 1, 'parch': 2, 'ticket': 'C.A. 2315', 'fare': 20.575, 'cabin': None, 'embarked': 'S'}

In [141]:
sql = "select * from titanic_raw where name like '%David%'"
cursor.execute(sql)

12

In [142]:
result = cursor.fetchall() # 쿼리에 실행결과를 다 가져오는 메소드 (한번 실행하면 사라진다.)
result[:4]

[{'passengerid': 113,
  'survived': 0,
  'pclass': 3,
  'name': 'Barton, Mr. David John',
  'gender': 'male',
  'age': 22.0,
  'sibsp': 0,
  'parch': 0,
  'ticket': '324669',
  'fare': 8.05,
  'cabin': None,
  'embarked': 'S'},
 {'passengerid': 150,
  'survived': 0,
  'pclass': 2,
  'name': 'Byles, Rev. Thomas Roussel Davids',
  'gender': 'male',
  'age': 42.0,
  'sibsp': 0,
  'parch': 0,
  'ticket': '244310',
  'fare': 13.0,
  'cabin': None,
  'embarked': 'S'},
 {'passengerid': 266,
  'survived': 0,
  'pclass': 2,
  'name': 'Reeves, Mr. David',
  'gender': 'male',
  'age': 36.0,
  'sibsp': 0,
  'parch': 0,
  'ticket': 'C.A. 17248',
  'fare': 10.5,
  'cabin': None,
  'embarked': 'S'},
 {'passengerid': 363,
  'survived': 0,
  'pclass': 3,
  'name': 'Barbara, Mrs. (Catherine David)',
  'gender': 'female',
  'age': 45.0,
  'sibsp': 0,
  'parch': 1,
  'ticket': '2691',
  'fare': 14.4542,
  'cabin': None,
  'embarked': 'C'}]

In [143]:
cursor.execute(sql)
for row in cursor.fetchall():
    print(row)

{'passengerid': 113, 'survived': 0, 'pclass': 3, 'name': 'Barton, Mr. David John', 'gender': 'male', 'age': 22.0, 'sibsp': 0, 'parch': 0, 'ticket': '324669', 'fare': 8.05, 'cabin': None, 'embarked': 'S'}
{'passengerid': 150, 'survived': 0, 'pclass': 2, 'name': 'Byles, Rev. Thomas Roussel Davids', 'gender': 'male', 'age': 42.0, 'sibsp': 0, 'parch': 0, 'ticket': '244310', 'fare': 13.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 266, 'survived': 0, 'pclass': 2, 'name': 'Reeves, Mr. David', 'gender': 'male', 'age': 36.0, 'sibsp': 0, 'parch': 0, 'ticket': 'C.A. 17248', 'fare': 10.5, 'cabin': None, 'embarked': 'S'}
{'passengerid': 363, 'survived': 0, 'pclass': 3, 'name': 'Barbara, Mrs. (Catherine David)', 'gender': 'female', 'age': 45.0, 'sibsp': 0, 'parch': 1, 'ticket': '2691', 'fare': 14.4542, 'cabin': None, 'embarked': 'C'}
{'passengerid': 398, 'survived': 0, 'pclass': 2, 'name': 'McKane, Mr. Peter David', 'gender': 'male', 'age': 46.0, 'sibsp': 0, 'parch': 0, 'ticket': '28403', 'fare': 26.0, 'cabin': None, 'embarked': 'S'}
{'passengerid': 422, 'survived': 0, 'pclass': 3, 'name': 'Charters, Mr. David', 'gender': 'male', 'age': 21.0, 'sibsp': 0, 'parch': 0, 'ticket': 'A/5. 13032', 'fare': 7.7333, 'cabin': None, 'embarked': 'Q'}
{'passengerid': 625, 'survived': 0, 'pclass': 3, 'name': 'Bowen, Mr. David John "Dai"', 'gender': 'male', 'age': 21.0, 'sibsp': 0, 'parch': 0, 'ticket': '54636', 'fare': 16.1, 'cabin': None, 'embarked': 'S'}
{'passengerid': 672, 'survived': 0, 'pclass': 1, 'name': 'Davidson, Mr. Thornton', 'gender': 'male', 'age': 31.0, 'sibsp': 1, 'parch': 0, 'ticket': 'F.C. 12750', 'fare': 52.0, 'cabin': 'B71', 'embarked': 'S'}
{'passengerid': 786, 'survived': 0, 'pclass': 3, 'name': 'Harmer, Mr. Abraham (David Lishin)', 'gender': 'male', 'age': 25.0, 'sibsp': 0, 'parch': 0, 'ticket': '374887', 'fare': 7.25, 'cabin': None, 'embarked': 'S'}
{'passengerid': 984, 'survived': 1, 'pclass': 1, 'name': 'Davidson, Mrs. Thornton (Orian Hays)', 'gender': 'female', 'age': 27.0, 'sibsp': 1, 'parch': 2, 'ticket': 'F.C. 12750', 'fare': 52.0, 'cabin': 'B71', 'embarked': 'S'}
{'passengerid': 1203, 'survived': 0, 'pclass': 3, 'name': 'Vartanian, Mr. David', 'gender': 'male', 'age': 22.0, 'sibsp': 0, 'parch': 0, 'ticket': '2658', 'fare': 7.225, 'cabin': None, 'embarked': 'C'}
{'passengerid': 1242, 'survived': 1, 'pclass': 1, 'name': 'Greenfield, Mrs. Leo David (Blanche Strouse)', 'gender': 'female', 'age': 45.0, 'sibsp': 0, 'parch': 1, 'ticket': 'PC 17759', 'fare': 63.3583, 'cabin': 'D10 D12', 'embarked': 'C'}

- 한행씩 가져오기

In [144]:
sql = "select * from titanic_raw;"
cursor.execute(sql)

1309

In [145]:
cursor.fetchone()

{'passengerid': 1,
 'survived': 0,
 'pclass': 3,
 'name': 'Braund, Mr. Owen Harris',
 'gender': 'male',
 'age': 22.0,
 'sibsp': 1,
 'parch': 0,
 'ticket': 'A/5 21171',
 'fare': 7.25,
 'cabin': None,
 'embarked': 'S'}

- 커서 닫아주기

In [146]:
cursor.closes()
sql = "select * from titanic_raw;"
cursor.execute(sql)

AttributeError: ignored

- with 문과 함께 사용하기
- 더 깔끔한 코드이다.

In [ ]:
with conn.cursor() as cursor: # cursor = conn.cursor()
    sql = "select * from titanic_raw;"
    cursor.execute(sql) # 커서가 닫혀있기 때문에 에러발생

- 연결 닫아주기

In [ ]:
conn.close()
cursor = conn.cursor()
sql = "select * from titanic_raw;"
cursor.execute(sql)

- DB 선택없이 접속

In [ ]:
conn = pymysql.connect(
    user = USER,
    host = HOST,
    passwd = PASSWD,
    port = PORT,
    # autocommit= True # 안좋은 습관
)
conn

In [ ]:
conn.autocommit_mode # 오토 커밋이 false로 되어있다.

- DB 선택하기

In [ ]:
conn.select_db("user11") # use DB명; DB 접속!

In [ ]:
cursor = conn.cursor(pymysql.cursors.DictCursor)
cursor

In [ ]:
!pip install git+https://github.com/DoItSon/api_project.git

In [ ]:
KEY_FILE = "/content/drive/MyDrive/data/local.yml"
with open(KEY_FILE,'r') as f:
    naver_keys = yaml.load(f,Loader = yaml.Loader)

In [147]:
from my_api import naver_api
url = "https://openapi.naver.com/v1/search/movie.json"
params = {
    "query" : "전우치",
}
result = naver_api.search_api(url,naver_keys["CLIENT_ID"],naver_keys["CLIENT_SECRET"],params)
result

{'lastBuildDate': 'Tue, 23 Aug 2022 12:31:17 +0900',
 'total': 5,
 'start': 1,
 'display': 5,
 'items': [{'title': '안녕, <b>전우치</b> 스페셜',
   'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=158852',
   'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/1588/158852_P01_130121.jpg',
   'subtitle': '',
   'pubDate': '2016',
   'director': '김대창|',
   'actor': '김율|김새해|정선혜|',
   'userRating': '10.00'},
  {'title': '안녕, <b>전우치</b>! 도술로봇대결전',
   'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=141421',
   'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/1414/141421_P23_142816.jpg',
   'subtitle': 'Hello, Jeonwoochi! The Robot Armageddon',
   'pubDate': '2015',
   'director': '김대창|',
   'actor': '김율|김새해|정선혜|홍범기|안장혁|류점희|',
   'userRating': '7.49'},
  {'title': '<b>전우치</b>',
   'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=86279',
   'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/0862/86279_P00_111154.jpg',
   'subtitle': '',
   'pubDate': '2012',
   'director': '강일수|',
   'actor': '차태현|유이|이희준|백진희|김갑수|성동일|',
   'userRating': '7.16'},
  {'title': '아저씨는 <b>전우치</b>와 악마를 보았다',
   'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=88964',
   'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/0889/88964_P01_194937.jpg',
   'subtitle': '',
   'pubDate': '2010',
   'director': '김탁훈|',
   'actor': '',
   'userRating': '9.35'},
  {'title': '<b>전우치</b>',
   'link': 'https://movie.naver.com/movie/bi/mi/basic.nhn?code=48227',
   'image': 'https://ssl.pstatic.net/imgmovie/mdi/mit110/0482/48227_P46_095817.jpg',
   'subtitle': 'Jeon Woochi : The Taoist Wizard',
   'pubDate': '2009',
   'director': '최동훈|',
   'actor': '강동원|김윤석|임수정|유해진|',
   'userRating': '8.21'}]}

- 테이블 만들기

In [148]:
sql = """
    create table if not exists tb_movie_info(
        id int unsigned not null auto_increment,
        actor varchar(255),
        director varchar(100),
        pubDate int,
        subtitle varchar(100),
        title varchar(100) not null,
        userRating float,
        primary key(id)
    );
"""
cursor.execute(sql)

0

In [149]:
movie_list = [
( "명량", 2014),
( "인터스텔라", 2014),
( "해적: 바다로 간 산적",  2014),
( "수상한 그녀",2014),
( "국제시장",2014),
( "트랜스포머: 사라진 시대",2014),
( "군도: 민란의 시대",2014),
( "엣지 오브 투모로우",2014),
( "엑스맨: 데이즈 오브 퓨처 패스트",2014),
( "어메이징 스파이더맨 2",2014),
( "타짜-신의 손",2014),
( "혹성탈출: 반격의 서막",2014),
( "캡틴 아메리카: 윈터 솔져",2014),
( "역린",2014),
( "신의 한 수",2014),
]

In [150]:
for title,year in movie_list:
    params = {"query" : title, "display" : 1,
              "yearfrom" : year, "yearto" : year}
    result = naver_api.search_api(url,
                                  naver_keys["CLIENT_ID"],
                                  naver_keys["CLIENT_SECRET"],
                                  params
                                  )
    sql = f'''
        insert into tb_movie_info(actor,director,pubDate,subtitle,title,userRating)
        values(
            '{result["items"][0]["actor"]}',
            '{result["items"][0]["director"]}',
            {result["items"][0]["pubDate"]},
            '{result["items"][0]["subtitle"]}',
            '{result["items"][0]["title"]}',
            {result["items"][0]["userRating"]}
        );
    '''
    cursor.execute(sql)

In [151]:
conn.commit() # 최종적으로 저장

- 잘 저장됐는지 확인해보자

In [152]:
sql= "select * from tb_movie_info;"
cursor.execute(sql)
cursor.fetchall()

[{'id': 1,
  'actor': '최민식|류승룡|조진웅|',
  'director': '김한민|',
  'pubDate': 2014,
  'subtitle': 'ROARING CURRENTS',
  'title': '<b>명량</b>',
  'userRating': 8.44},
 {'id': 2,
  'actor': '매튜 맥커너히|앤 해서웨이|마이클 케인|제시카 차스테인|',
  'director': '크리스토퍼 놀란|',
  'pubDate': 2014,
  'subtitle': 'Interstellar',
  'title': '<b>인터스텔라</b>',
  'userRating': 9.11},
 {'id': 3,
  'actor': '김남길|손예진|',
  'director': '이석훈|',
  'pubDate': 2014,
  'subtitle': 'The Pirates',
  'title': '<b>해적: 바다로 간 산적</b>',
  'userRating': 8.28},
 {'id': 4,
  'actor': '심은경|나문희|박인환|성동일|이진욱|',
  'director': '황동혁|',
  'pubDate': 2014,
  'subtitle': 'Miss Granny',
  'title': '<b>수상한 그녀</b>',
  'userRating': 9.01},
 {'id': 5,
  'actor': '황정민|김윤진|오달수|정진영|',
  'director': '윤제균|',
  'pubDate': 2014,
  'subtitle': 'Ode to My Father',
  'title': '<b>국제시장</b>',
  'userRating': 9.02},
 {'id': 6,
  'actor': '마크 월버그|니콜라 펠츠|잭 레이너|스탠리 투치|리빙빙|',
  'director': '마이클 베이|',
  'pubDate': 2014,
  'subtitle': 'Transformers: Age of Extinction',
  'title': '<b>트랜스포머: 사라진 시대</b>',
  'userRating': 6.58},
 {'id': 7,
  'actor': '하정우|강동원|',
  'director': '윤종빈|',
  'pubDate': 2014,
  'subtitle': 'KUNDO : Age of the Rampant',
  'title': '<b>군도:민란의 시대</b>',
  'userRating': 6.94},
 {'id': 8,
  'actor': '톰 크루즈|에밀리 블런트|빌 팩스톤|',
  'director': '더그 라이만|',
  'pubDate': 2014,
  'subtitle': 'Edge of Tomorrow',
  'title': '<b>엣지 오브 투모로우</b>',
  'userRating': 8.96},
 {'id': 9,
  'actor': '제니퍼 로렌스|휴 잭맨|제임스 맥어보이|마이클 패스벤더|',
  'director': '브라이언 싱어|',
  'pubDate': 2014,
  'subtitle': 'X-Men: Days of Future Past',
  'title': '<b>엑스맨: 데이즈 오브 퓨처 패스트</b>',
  'userRating': 8.89},
 {'id': 10,
  'actor': '엠마 스톤|앤드류 가필드|',
  'director': '마크 웹|',
  'pubDate': 2014,
  'subtitle': 'The Amazing Spider-Man <b>2</b>',
  'title': '<b>어메이징 스파이더맨 2</b>',
  'userRating': 7.77},
 {'id': 11,
  'actor': 'T.O.P|신세경|곽도원|이하늬|',
  'director': '강형철|',
  'pubDate': 2014,
  'subtitle': 'Tazza-The Hidden Card',
  'title': '<b>타짜-신의 손</b>',
  'userRating': 7.25},
 {'id': 12,
  'actor': '앤디 서키스|게리 올드만|제이슨 클락|주디 그리어|케리 러셀|',
  'director': '맷 리브스|',
  'pubDate': 2014,
  'subtitle': 'Dawn of the Planet of the Apes',
  'title': '<b>혹성탈출: 반격의 서막</b>',
  'userRating': 8.54},
 {'id': 13,
  'actor': '스칼릿 조핸슨|크리스 에반스|사무엘 L. 잭슨|',
  'director': '조 루소|앤서니 루소|',
  'pubDate': 2014,
  'subtitle': 'Captain America: The Winter Soldier',
  'title': '<b>캡틴 아메리카: 윈터 솔져</b>',
  'userRating': 8.93},
 {'id': 14,
  'actor': '현빈|정재영|조정석|조재현|한지민|',
  'director': '이재규|',
  'pubDate': 2014,
  'subtitle': 'The Fatal Encounter',
  'title': '<b>역린</b>',
  'userRating': 7.09},
 {'id': 15,
  'actor': '정우성|이범수|안성기|김인권|이시영|',
  'director': '조범구|',
  'pubDate': 2014,
  'subtitle': 'The Divine Move',
  'title': '<b>신의 한 수</b>',
  'userRating': 8.02}]

- insert 한번에 실행해서 속도 개선

In [153]:
            #  '{result["items"][0]["actor"]}',
            # '{result["items"][0]["director"]}',
            # {result["items"][0]["pubDate"]},
            # '{result["items"][0]["subtitle"]}',
            # '{result["items"][0]["title"]}',
            # {result["items"][0]["userRating"]}

In [154]:
values_list = []
for title,year in movie_list:
    params=     params = {"query" : title, "display" : 1,
              "yearfrom" : year, "yearto" : year}
    result = naver_api.search_api(url,
                                  naver_keys["CLIENT_ID"],
                                  naver_keys["CLIENT_SECRET"],
                                  params
                                  )
    values = (
    result["items"][0]["actor"],
    result["items"][0]["director"],
    result["items"][0]["pubDate"],
    result["items"][0]["subtitle"],
    result["items"][0]["title"],
    result["items"][0]["userRating"]
    )
    values_list.append(values)

In [155]:
values_list[0]

('최민식|류승룡|조진웅|', '김한민|', '2014', 'ROARING CURRENTS', '<b>명량</b>', '8.44')

In [156]:
sql = '''
    insert into tb_movie_info(actor,director,pubDate,subtitle,title,userRating)
    values(%s, %s, %s, %s, %s, %s);
'''
cursor.executemany(sql,values_list) # 속도가 빠르다!

15

In [157]:
conn.rollback() # 롤백하여 저장안함!

In [158]:
sql = "select * from tb_movie_info;"
cursor.execute(sql)
cursor.fetchall()

[{'id': 1,
  'actor': '최민식|류승룡|조진웅|',
  'director': '김한민|',
  'pubDate': 2014,
  'subtitle': 'ROARING CURRENTS',
  'title': '<b>명량</b>',
  'userRating': 8.44},
 {'id': 2,
  'actor': '매튜 맥커너히|앤 해서웨이|마이클 케인|제시카 차스테인|',
  'director': '크리스토퍼 놀란|',
  'pubDate': 2014,
  'subtitle': 'Interstellar',
  'title': '<b>인터스텔라</b>',
  'userRating': 9.11},
 {'id': 3,
  'actor': '김남길|손예진|',
  'director': '이석훈|',
  'pubDate': 2014,
  'subtitle': 'The Pirates',
  'title': '<b>해적: 바다로 간 산적</b>',
  'userRating': 8.28},
 {'id': 4,
  'actor': '심은경|나문희|박인환|성동일|이진욱|',
  'director': '황동혁|',
  'pubDate': 2014,
  'subtitle': 'Miss Granny',
  'title': '<b>수상한 그녀</b>',
  'userRating': 9.01},
 {'id': 5,
  'actor': '황정민|김윤진|오달수|정진영|',
  'director': '윤제균|',
  'pubDate': 2014,
  'subtitle': 'Ode to My Father',
  'title': '<b>국제시장</b>',
  'userRating': 9.02},
 {'id': 6,
  'actor': '마크 월버그|니콜라 펠츠|잭 레이너|스탠리 투치|리빙빙|',
  'director': '마이클 베이|',
  'pubDate': 2014,
  'subtitle': 'Transformers: Age of Extinction',
  'title': '<b>트랜스포머: 사라진 시대</b>',
  'userRating': 6.58},
 {'id': 7,
  'actor': '하정우|강동원|',
  'director': '윤종빈|',
  'pubDate': 2014,
  'subtitle': 'KUNDO : Age of the Rampant',
  'title': '<b>군도:민란의 시대</b>',
  'userRating': 6.94},
 {'id': 8,
  'actor': '톰 크루즈|에밀리 블런트|빌 팩스톤|',
  'director': '더그 라이만|',
  'pubDate': 2014,
  'subtitle': 'Edge of Tomorrow',
  'title': '<b>엣지 오브 투모로우</b>',
  'userRating': 8.96},
 {'id': 9,
  'actor': '제니퍼 로렌스|휴 잭맨|제임스 맥어보이|마이클 패스벤더|',
  'director': '브라이언 싱어|',
  'pubDate': 2014,
  'subtitle': 'X-Men: Days of Future Past',
  'title': '<b>엑스맨: 데이즈 오브 퓨처 패스트</b>',
  'userRating': 8.89},
 {'id': 10,
  'actor': '엠마 스톤|앤드류 가필드|',
  'director': '마크 웹|',
  'pubDate': 2014,
  'subtitle': 'The Amazing Spider-Man <b>2</b>',
  'title': '<b>어메이징 스파이더맨 2</b>',
  'userRating': 7.77},
 {'id': 11,
  'actor': 'T.O.P|신세경|곽도원|이하늬|',
  'director': '강형철|',
  'pubDate': 2014,
  'subtitle': 'Tazza-The Hidden Card',
  'title': '<b>타짜-신의 손</b>',
  'userRating': 7.25},
 {'id': 12,
  'actor': '앤디 서키스|게리 올드만|제이슨 클락|주디 그리어|케리 러셀|',
  'director': '맷 리브스|',
  'pubDate': 2014,
  'subtitle': 'Dawn of the Planet of the Apes',
  'title': '<b>혹성탈출: 반격의 서막</b>',
  'userRating': 8.54},
 {'id': 13,
  'actor': '스칼릿 조핸슨|크리스 에반스|사무엘 L. 잭슨|',
  'director': '조 루소|앤서니 루소|',
  'pubDate': 2014,
  'subtitle': 'Captain America: The Winter Soldier',
  'title': '<b>캡틴 아메리카: 윈터 솔져</b>',
  'userRating': 8.93},
 {'id': 14,
  'actor': '현빈|정재영|조정석|조재현|한지민|',
  'director': '이재규|',
  'pubDate': 2014,
  'subtitle': 'The Fatal Encounter',
  'title': '<b>역린</b>',
  'userRating': 7.09},
 {'id': 15,
  'actor': '정우성|이범수|안성기|김인권|이시영|',
  'director': '조범구|',
  'pubDate': 2014,
  'subtitle': 'The Divine Move',
  'title': '<b>신의 한 수</b>',
  'userRating': 8.02}]

- pymysql의 연결 객체를 이용하여 pandas의 자료형인 데이터프레임 객체 생성하기

In [160]:
import pandas as pd
df = pd.read_sql("select * from titanic_raw",conn)

In [162]:
df.head(5)

,passengerid,survived,pclass,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [169]:
pd.read_sql("show tables",conn)

  Tables_in_playdata
0               dept
1                emp
2      tb_movie_info
3        titanic_raw

In [165]:
pd.read_sql("desc titanic_raw",conn)

          Field          Type Null  Key Default Extra
0   passengerid           int   NO  PRI    None
1      survived           int  YES         None
2        pclass           int  YES         None
3          name  varchar(100)  YES         None
4        gender   varchar(50)  YES         None
5           age        double  YES         None
6         sibsp           int  YES         None
7         parch           int  YES         None
8        ticket   varchar(80)  YES         None
9          fare        double  YES         None
10        cabin   varchar(50)  YES         None
11     embarked   varchar(20)  YES         None

In [175]:
pd.read_sql("select name,gender,age,sibsp,parch,ticket from titanic_raw where embarked = 'S' and survived = 1",conn)

,name,gender,age,sibsp,parch,ticket
0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282
1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803
2,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742
3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549
4,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783
...,...,...,...,...,...,...
300,"Lines, Mrs. Ernest H (Elizabeth Lindsey James)",female,51.0,0,1,PC 17592
301,"Smith, Mrs. Lucien Philip (Mary Eloise Hughes)",female,18.0,1,0,13695
302,"Bonnell, Miss. Caroline",female,30.0,0,0,36928
303,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315
304,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086

In [176]:
conn.close()