<a href="https://colab.research.google.com/github/DoItSon/playdata/blob/main/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D/02_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scikit-learn
- https://scikit-learn.org/stable/#
- 다양한 머신러닝 관련한 기술들을 통일되고 쉬운 인터페이스로 사용할수 있게 해주는 라이브러리
- 머신러닝 관련 알고리즘과 개발을 위한 기능 제공

## Getting Started with scikit-learn(자주 사용하는 사이킷런 모듈)
- 데이터 정제(Data Cleasing) & 속성 공학(Feature Engineering)
    - sklearn.preprocessing: 데이터 전처리(인코딩, 정규화 등)
    - sklearn.feature_selection: 특성 선택
    - sklearn.feature_extraction: 특성 추출(이미지나 텍스트에서 속성 추출)
- 모형 성능 평가와 개선
    - sklearn.model_selection: 데이터 분리, 하이퍼 파라미터 튜닝
    - sklearn.metrics: 성능평가
- 지도학습(Supervised Learning) 알고리즘
    - sklearn.ensemble: 앙상블 알고리즘
    - sklearn.linear_model: 선형모델(선형회귀, 로지스틱회귀 등)
    - sklearn.tree: 의사결정나무(Decision Trees)
- 비지도학습(Unsupervised Learning) 알고리즘
    - sklearn.cluster: 군집분석
    - sklearn.decomposition: 차원축소
- 유틸리티와 데이터 세트
    - sklearn.pipeline: 워크플로우 효율화
    - sklearn.datasets: 예제 데이터 세트(iris, digits 데이터 등)

- 사이킷런에서는 분류 알고리즘을 구현한 모델 클래스를 Classifier, 회귀 알고리즘을 구현한 모델 클래스를 Regressor로 지칭
    - Ex) DecisionTreeClassifier(분류문제에 사용하는 의사결정나무) vs. DecisionTreeRegressor(회귀문제에 사용하는 의사결정나무)
    - Classifier와 Regressor를 합쳐서 Estimator 클래스라고 함
    
- API 사용 방법
    - ML 학습을 위해 fit()을, 예측을 위해 predict()
    - 데이터 변환을 위해 fit(), fit_transform(), transform()

# 데이터 불러오기
- 유방암 진단 자료

In [ ]:
from sklearn.datasets import load_breast_cancer
load_breast_cancer()

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry\n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        worst/largest values) of these features were computed for each image,\n        resulting in 30 features.  For instance, field 0 is Mean Radius, field\n        10 is Radius SE, field 20 is Worst Radius.\n\n        - class:\n                - WDBC-Malignant\n                - WDBC-Benign\n\n    :Summary Statistics:\n\n    ===================================== ====== ======\n                                           Min    Max\n    ===================================== ====== ======\n    radius (mean):                        6.981  28.11\n    texture (mean):                       9.71   39.28\n    perimeter (mean):                     43.79  188.5\n    area (mean):                          143.5  2501.0\n    smoothness (mean):                    0.053  0.163\n    compactness (mean):                   0.019  0.345\n    concavity (mean):                     0.0    0.427\n    concave points (mean):                0.0    0.201\n    symmetry (mean):                      0.106  0.304\n    fractal dimension (mean):             0.05   0.097\n    radius (standard error):              0.112  2.873\n    texture (standard error):             0.36   4.885\n    perimeter (standard error):           0.757  21.98\n    area (standard error):                6.802  542.2\n    smoothness (standard error):          0.002  0.031\n    compactness (standard error):         0.002  0.135\n    concavity (standard error):           0.0    0.396\n    concave points (standard error):      0.0    0.053\n    symmetry (standard error):            0.008  0.079\n    fractal dimension (standard error):   0.001  0.03\n    radius (worst):                       7.93   36.04\n    texture (worst):                      12.02  49.54\n    perimeter (worst):                    50.41  251.2\n    area (worst):                         185.2  4254.0\n    smoothness (worst):                   0.071  0.223\n    compactness (worst):                  0.027  1.058\n    concavity (worst):                    0.0    1.252\n    concave points (worst):               0.0    0.291\n    symmetry (worst):                     0.156  0.664\n    fractal dimension (worst):            0.055  0.208\n    ===================================== ====== ======\n\n    :Missing Attribute Values: None\n\n    :Class Distribution: 212 - Malignant, 357 - Benign\n\n    :Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n    :Donor: Nick Street\n\n    :Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. topic:: References\n\n   - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction \n     for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on \n     Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n     San Jose, CA, 1993.\n   - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and \n     prognosis via linear programming. Operations Research, 43(4), pages 570-577, \n     July-August 1995.\n   - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n     to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994) \n     163-171.',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [ ]:
breast_cancer = load_breast_cancer()
breast_cancer.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
breast_cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
breast_cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
import numpy as np
import pandas as pd

data = pd.DataFrame(breast_cancer.data,columns = breast_cancer.feature_names)
data.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
data.info() # 항상 info 먼저보기! (결축치 없고, 소수형)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
dtypes: float64(30)
memory usage: 133.5 KB

In [ ]:
data.nunique() # 범주형 데이터는 없다. (항상 확인 필요)

mean radius                456
mean texture               479
mean perimeter             522
mean area                  539
mean smoothness            474
mean compactness           537
mean concavity             537
mean concave points        542
mean symmetry              432
mean fractal dimension     499
radius error               540
texture error              519
perimeter error            533
area error                 528
smoothness error           547
compactness error          541
concavity error            533
concave points error       507
symmetry error             498
fractal dimension error    545
worst radius               457
worst texture              511
worst perimeter            514
worst area                 544
worst smoothness           411
worst compactness          529
worst concavity            539
worst concave points       492
worst symmetry             500
worst fractal dimension    535
dtype: int64

In [ ]:
data["target"] = breast_cancer.target
data.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [ ]:
data["target"].mean() # 1에 대한 평균이 62% (중점을 두는 클래스를 1로 둔다!)

0.6274165202108963

# Data Preprocessing

## 특성 데이터와 정답값을 분리

In [ ]:
x_data = data.iloc[:,:-1] # 정답값을 제외하고, 특성값을 슬라이싱
y_data = data["target"]

x_data.shape, y_data.shape

((569, 30), (569,))

## Feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
x_data = scaler.fit_transform(x_data) # 데이터프레임을 넣었고, 반환은 Numpy 배열형태로 된다.
x_data.shape

(569, 30)

## 학습데이터와 검증데이터로 분리 (training set 과정)

In [ ]:
SEED = 42

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(x_data, y_data, test_size = 0.2, random_state = SEED) # test_size(학습의 정답데이터)는 8 대 2 정도가 적당해서 0.2
x_train.shape, x_valid.shape, y_train.shape, y_valid.shape

((455, 30), (114, 30), (455,), (114,))

## 학습하기

In [ ]:
from sklearn.linear_model import LogisticRegression # 2진분류형

model = LogisticRegression(random_state = SEED) # 모델 만듦!

model.fit(x_train,y_train) # 학습완료

LogisticRegression(random_state=42)

## 검증셋 평가하기

In [ ]:
pred = model.predict(x_valid)
pred[:5]

array([1, 0, 0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_valid,pred) # 정답값,예측값을 넣음 (정확도 98%)

0.9824561403508771

In [ ]:
model.predict_proba(x_valid) # 확률로 예측하기 (1열 = 0에대한 확률, 2열 = 1에대한 확률)

array([[1.78646356e-01, 8.21353644e-01],
       [9.66644486e-01, 3.33555144e-02],
       [8.35057498e-01, 1.64942502e-01],
       [5.79443795e-02, 9.42055620e-01],
       [1.99255465e-02, 9.80074454e-01],
       [9.99926935e-01, 7.30650746e-05],
       [9.99261480e-01, 7.38519501e-04],
       [6.99523459e-01, 3.00476541e-01],
       [4.80857468e-01, 5.19142532e-01],
       [4.02872723e-02, 9.59712728e-01],
       [1.30302480e-01, 8.69697520e-01],
       [7.39075630e-01, 2.60924370e-01],
       [8.41426988e-02, 9.15857301e-01],
       [6.74476214e-01, 3.25523786e-01],
       [4.20547907e-02, 9.57945209e-01],
       [9.79478506e-01, 2.05214941e-02],
       [5.39641679e-02, 9.46035832e-01],
       [7.22201007e-03, 9.92777990e-01],
       [1.49630372e-03, 9.98503696e-01],
       [9.94375960e-01, 5.62404030e-03],
       [2.68786507e-01, 7.31213493e-01],
       [7.78053145e-02, 9.22194686e-01],
       [9.99501319e-01, 4.98680766e-04],
       [8.69447849e-03, 9.91305522e-01],
       [3.80445401e-02, 9.61955460e-01],
       [5.43628122e-02, 9.45637188e-01],
       [5.11276082e-02, 9.48872392e-01],
       [7.49326859e-02, 9.25067314e-01],
       [6.42843058e-02, 9.35715694e-01],
       [9.90476631e-01, 9.52336883e-03],
       [3.99078239e-02, 9.60092176e-01],
       [1.68784459e-02, 9.83121554e-01],
       [2.23491730e-02, 9.77650827e-01],
       [6.77226210e-02, 9.32277379e-01],
       [1.61973339e-02, 9.83802666e-01],
       [3.46809841e-02, 9.65319016e-01],
       [5.33807467e-01, 4.66192533e-01],
       [2.35310701e-02, 9.76468930e-01],
       [9.59758524e-01, 4.02414764e-02],
       [1.76523770e-01, 8.23476230e-01],
       [1.50262703e-02, 9.84973730e-01],
       [8.65136173e-01, 1.34863827e-01],
       [6.85388434e-02, 9.31461157e-01],
       [3.49654251e-02, 9.65034575e-01],
       [7.35040231e-02, 9.26495977e-01],
       [9.88046786e-02, 9.01195321e-01],
       [2.14202921e-02, 9.78579708e-01],
       [1.31736834e-02, 9.86826317e-01],
       [1.17713654e-01, 8.82286346e-01],
       [4.74700423e-02, 9.52529958e-01],
       [9.48444680e-01, 5.15553203e-02],
       [9.96884754e-01, 3.11524617e-03],
       [3.68745729e-01, 6.31254271e-01],
       [1.13908772e-01, 8.86091228e-01],
       [2.02912036e-02, 9.79708796e-01],
       [8.56987158e-02, 9.14301284e-01],
       [2.40556212e-02, 9.75944379e-01],
       [9.99970392e-01, 2.96079933e-05],
       [6.88780606e-01, 3.11219394e-01],
       [1.80930819e-02, 9.81906918e-01],
       [7.84938250e-02, 9.21506175e-01],
       [9.95310963e-01, 4.68903684e-03],
       [9.97933497e-01, 2.06650295e-03],
       [1.36898030e-01, 8.63101970e-01],
       [2.54289250e-02, 9.74571075e-01],
       [2.02923050e-01, 7.97076950e-01],
       [9.81026628e-01, 1.89733718e-02],
       [9.99775808e-01, 2.24192269e-04],
       [3.07793603e-02, 9.69220640e-01],
       [1.39396195e-01, 8.60603805e-01],
       [8.23750468e-01, 1.76249532e-01],
       [8.86811885e-01, 1.13188115e-01],
       [6.46699746e-02, 9.35330025e-01],
       [9.15519538e-01, 8.44804619e-02],
       [5.44745552e-03, 9.94552544e-01],
       [1.35727656e-01, 8.64272344e-01],
       [1.17666416e-01, 8.82333584e-01],
       [4.18062733e-01, 5.81937267e-01],
       [6.58619159e-03, 9.93413808e-01],
       [1.11588569e-01, 8.88411431e-01],
       [8.42951730e-01, 1.57048270e-01],
       [8.23163631e-03, 9.91768364e-01],
       [5.13373042e-01, 4.86626958e-01],
       [9.98094117e-01, 1.90588343e-03],
       [8.21799825e-01, 1.78200175e-01],
       [9.48266943e-01, 5.17330574e-02],
       [9.77691287e-01, 2.23087129e-02],
       [9.66625743e-01, 3.33742571e-02],
       [5.11431575e-02, 9.48856843e-01],
       [7.75534563e-02, 9.22446544e-01],
       [6.60686916e-02, 9.33931308e-01],
       [3.33502033e-01, 6.66497967e-01],
       [1.88786520e-01, 8.11213480e-01],
       [1.78972818e-02, 9.82102718e-01],
       [2.21523507e-02, 9.77847649e-01],
       [1.23287606e-02, 9.87671239e-01],
       [9.90556983e-01, 9.44301716e-03],
       [9.88436270e-01, 1.15637295e-02],
       [1.05272643e-02, 9.89472736e-01],
       [9.40291561e-01, 5.97084393e-02],
       [8.20824204e-01, 1.79175796e-01],
       [1.97765222e-03, 9.98022348e-01],
       [9.76153178e-01, 2.38468218e-02],
       [9.46453381e-01, 5.35466190e-02],
       [4.27350373e-02, 9.57264963e-01],
       [9.84713182e-02, 9.01528682e-01],
       [9.06696610e-02, 9.09330339e-01],
       [9.99032140e-01, 9.67860147e-04],
       [2.91894294e-01, 7.08105706e-01],
       [1.34619148e-01, 8.65380852e-01],
       [7.93923917e-01, 2.06076083e-01],
       [4.08367366e-02, 9.59163263e-01],
       [4.06201602e-01, 5.93798398e-01],
       [9.99731209e-01, 2.68790646e-04]])

In [ ]:
model.predict_proba(x_valid)[:,1] # 1열만 가져옴

array([8.21353644e-01, 3.33555144e-02, 1.64942502e-01, 9.42055620e-01,
       9.80074454e-01, 7.30650746e-05, 7.38519501e-04, 3.00476541e-01,
       5.19142532e-01, 9.59712728e-01, 8.69697520e-01, 2.60924370e-01,
       9.15857301e-01, 3.25523786e-01, 9.57945209e-01, 2.05214941e-02,
       9.46035832e-01, 9.92777990e-01, 9.98503696e-01, 5.62404030e-03,
       7.31213493e-01, 9.22194686e-01, 4.98680766e-04, 9.91305522e-01,
       9.61955460e-01, 9.45637188e-01, 9.48872392e-01, 9.25067314e-01,
       9.35715694e-01, 9.52336883e-03, 9.60092176e-01, 9.83121554e-01,
       9.77650827e-01, 9.32277379e-01, 9.83802666e-01, 9.65319016e-01,
       4.66192533e-01, 9.76468930e-01, 4.02414764e-02, 8.23476230e-01,
       9.84973730e-01, 1.34863827e-01, 9.31461157e-01, 9.65034575e-01,
       9.26495977e-01, 9.01195321e-01, 9.78579708e-01, 9.86826317e-01,
       8.82286346e-01, 9.52529958e-01, 5.15553203e-02, 3.11524617e-03,
       6.31254271e-01, 8.86091228e-01, 9.79708796e-01, 9.14301284e-01,
       9.75944379e-01, 2.96079933e-05, 3.11219394e-01, 9.81906918e-01,
       9.21506175e-01, 4.68903684e-03, 2.06650295e-03, 8.63101970e-01,
       9.74571075e-01, 7.97076950e-01, 1.89733718e-02, 2.24192269e-04,
       9.69220640e-01, 8.60603805e-01, 1.76249532e-01, 1.13188115e-01,
       9.35330025e-01, 8.44804619e-02, 9.94552544e-01, 8.64272344e-01,
       8.82333584e-01, 5.81937267e-01, 9.93413808e-01, 8.88411431e-01,
       1.57048270e-01, 9.91768364e-01, 4.86626958e-01, 1.90588343e-03,
       1.78200175e-01, 5.17330574e-02, 2.23087129e-02, 3.33742571e-02,
       9.48856843e-01, 9.22446544e-01, 9.33931308e-01, 6.66497967e-01,
       8.11213480e-01, 9.82102718e-01, 9.77847649e-01, 9.87671239e-01,
       9.44301716e-03, 1.15637295e-02, 9.89472736e-01, 5.97084393e-02,
       1.79175796e-01, 9.98022348e-01, 2.38468218e-02, 5.35466190e-02,
       9.57264963e-01, 9.01528682e-01, 9.09330339e-01, 9.67860147e-04,
       7.08105706e-01, 8.65380852e-01, 2.06076083e-01, 9.59163263e-01,
       5.93798398e-01, 2.68790646e-04])

## 머신러닝 모델링 과정
```
데이터 전처리 -> 데이터 셋 분리 -> 모델생성 및 학습 -> 예측 수행 -> 평가
```

# 백화점 데이터셋 모델링

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DATA_PATH = "/content/drive/MyDrive/data/"
tr_train = pd.read_csv(f"{DATA_PATH}trans_train.csv")
target_train = pd.read_csv(f"{DATA_PATH}target_train.csv")

tr_train.shape , target_train.shape

((167465, 7), (2554, 2))

In [ ]:
target_train.target.mean() # 남자 37% (1%미만이면 불균형)

0.37196554424432265

## 데이터 전처리

### feature Engineering

In [ ]:
tr_train["구매일자"] = pd.to_datetime(tr_train["구매일자"])
agg_dict = {
    '구매일자':[
        ("내점일수","nunique"),
        ("구매주기",lambda x : (x.max() - x.min()).days / x.nunique() ), # 최근 구매일과 최초 구매일의 차이를 구하고 내점일수로 나누면 구매주기라고 볼수있음
        ("주말방문비율", lambda x : (x.dt.weekday > 4).mean() ), # 4보다 크면 토,일 이니까!!
        ("주구매요일" , lambda x: x.dt.weekday.mode()[0] ), # 최빈값이 여러개 일수도 있어서..
        ("봄구매비율" , lambda x : (x.dt.month.isin([3,4,5])).mean() ),
        ("여름구매비율" , lambda x : (x.dt.month.isin([6,7,8])).mean() ),
        ("가을구매비율" , lambda x : (x.dt.month.isin([9,10,11])).mean() ),
        ("겨울구매비율" , lambda x : (x.dt.month.isin([12,1,2])).mean() ),
        ("일평균구매건수" , lambda x : x.count() / x.nunique() ), # 구매건수를 구매일자로 나누면 일평균 구매건수라고 볼수있음.
        ("거래개월수" , lambda x : x.dt.month.nunique() )
    ],
    '지점':[
         ("방문지점수","nunique"),
         ("주구매지점" , lambda x : x.mode()[0])
    ],
    '상품번호': [
             ('상품번호수', 'nunique'),
             ],
    '중분류': [
            ('중분류수', 'nunique'),
            ('주구매중분류', lambda x: x.mode()[0]),
            ],
    '대분류': [
            ('대분류수', 'nunique'),
            ('주구매대분류', lambda x: x.mode()[0]),
            ],
    '구매가격' : [
        ('총구매액','sum'),
        ('구매건수', 'count'),
        ('평균구매액', "mean"),
        ('최대구매액', 'max'),
        ('최소구매액',lambda x: x[x > 0].min() ) ,
        ('환불금액',lambda x: x[x < 0].sum() ) ,
        ('환불건수', lambda x: ( x < 0 ).sum() ),
        ('구매금액표준편차',lambda x: x[x>0].std() ),
    ],
}
tmp = tr_train.groupby('고객번호').agg(agg_dict)
tmp.columns = tmp.columns.droplevel()
tmp = tmp.reset_index()
target_train = target_train.merge(tmp,how="left",on = "고객번호")
target_train

,고객번호,target,내점일수,구매주기,주말방문비율,주구매요일,봄구매비율,여름구매비율,가을구매비율,겨울구매비율,...,대분류수,주구매대분류,총구매액,구매건수,평균구매액,최대구매액,최소구매액,환불금액,환불건수,구매금액표준편차
0,10004,1,26,11.423077,0.617647,5,0.161765,0.397059,0.250000,0.191176,...,25,가공식품,390166360,68,5.737741e+06,41760000,6570.0,-4700000,1,9.453819e+06
1,10013,0,11,21.090909,0.117647,4,0.352941,0.235294,0.352941,0.058824,...,9,가공식품,22447800,17,1.320459e+06,13375000,6900.0,0,0,3.179888e+06
2,10023,0,21,16.666667,0.348837,3,0.348837,0.162791,0.232558,0.255814,...,17,골프,81765810,43,1.901530e+06,14325000,1250.0,-6003000,1,3.738478e+06
3,10040,0,24,13.833333,0.121212,4,0.272727,0.151515,0.318182,0.257576,...,15,명품,213705680,66,3.237965e+06,24738000,1500.0,-12948000,3,5.883481e+06
4,10052,0,28,8.892857,0.333333,2,0.585586,0.243243,0.171171,0.000000,...,20,시티웨어,358336570,111,3.228257e+06,38328000,1250.0,-30868000,3,6.959274e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2549,49813,0,83,4.253012,0.167116,1,0.226415,0.339623,0.237197,0.196765,...,20,가공식품,47428060,371,1.278384e+05,9120000,1000.0,-1532000,2,5.931527e+05
2550,49892,0,31,10.096774,0.363636,6,0.181818,0.289256,0.380165,0.148760,...,20,농산물,54369820,121,4.493374e+05,7500000,1100.0,0,0,1.148466e+06
2551,49925,0,3,18.333333,0.333333,3,0.000000,1.000000,0.000000,0.000000,...,1,명품,1657400,3,5.524667e+05,1015000,39000.0,0,0,4.899894e+05
2552,49943,0,7,30.285714,0.545455,5,0.090909,0.545455,0.272727,0.090909,...,7,농산물,40742400,11,3.703855e+06,21780000,36000.0,0,0,6.610017e+06
2553,49974,0,5,35.600000,0.047619,3,0.523810,0.095238,0.380952,0.000000,...,10,가공식품,7273000,21,3.463333e+05,2205000,5000.0,0,0,5.858956e+05

In [ ]:
target_train.info() # object = 범주형

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2554 entries, 0 to 2553
Data columns (total 27 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   고객번호      2554 non-null   int64
 1   target    2554 non-null   int64
 2   내점일수      2554 non-null   int64
 3   구매주기      2554 non-null   float64
 4   주말방문비율    2554 non-null   float64
 5   주구매요일     2554 non-null   int64
 6   봄구매비율     2554 non-null   float64
 7   여름구매비율    2554 non-null   float64
 8   가을구매비율    2554 non-null   float64
 9   겨울구매비율    2554 non-null   float64
 10  일평균구매건수   2554 non-null   float64
 11  거래개월수     2554 non-null   int64
 12  방문지점수     2554 non-null   int64
 13  주구매지점     2554 non-null   object
 14  상품번호수     2554 non-null   int64
 15  중분류수      2554 non-null   int64
 16  주구매중분류    2554 non-null   object
 17  대분류수      2554 non-null   int64
 18  주구매대분류    2554 non-null   object
 19  총구매액      2554 non-null   int64
 20  구매건수      2554 non-null   int64
 21  평균구매액     2554 non-null   float64
 22  최대구매액     2554 non-null   int64
 23  최소구매액     2553 non-null   float64
 24  환불금액      2554 non-null   int64
 25  환불건수      2554 non-null   int64
 26  구매금액표준편차  2321 non-null   float64
dtypes: float64(10), int64(14), object(3)
memory usage: 558.7+ KB

### 결측치 채우기

In [ ]:
target_train.isnull().sum() # 결측치 확인!

고객번호          0
target        0
내점일수          0
구매주기          0
주말방문비율        0
주구매요일         0
봄구매비율         0
여름구매비율        0
가을구매비율        0
겨울구매비율        0
일평균구매건수       0
거래개월수         0
방문지점수         0
주구매지점         0
상품번호수         0
중분류수          0
주구매중분류        0
대분류수          0
주구매대분류        0
총구매액          0
구매건수          0
평균구매액         0
최대구매액         0
최소구매액         1
환불금액          0
환불건수          0
구매금액표준편차    233
dtype: int64

In [ ]:
target_train = target_train.fillna(0)
target_train.isnull().sum().sum() # 0으로 채워진 것 확인!

0

### 범주형 Encoding

In [ ]:
target_train.select_dtypes("object").nunique() # 50개까지는 원핫인코딩 가능!

주구매지점      24
주구매중분류    169
주구매대분류     40
dtype: int64

In [ ]:
cols = target_train.select_dtypes("object").columns
cols

Index(['주구매지점', '주구매중분류', '주구매대분류'], dtype='object')

- OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
enc.fit_transform(target_train[cols]).toarray() # toarray를 통해 넘파이 배열로 변환한다.

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
enc.get_feature_names_out() # 원핫인코딩의 컬럼명이 담겨있다.

array(['주구매지점_강남점', '주구매지점_관악점', '주구매지점_광주점', '주구매지점_노원점', '주구매지점_대구점',
       '주구매지점_대전점', '주구매지점_동래점', '주구매지점_미아점', '주구매지점_본  점', '주구매지점_부산본점',
       '주구매지점_부평점', '주구매지점_분당점', '주구매지점_상인점', '주구매지점_센텀시티점', '주구매지점_안양점',
       '주구매지점_영등포점', '주구매지점_울산점', '주구매지점_인천점', '주구매지점_일산점', '주구매지점_잠실점',
       '주구매지점_전주점', '주구매지점_창원점', '주구매지점_청량리점', '주구매지점_포항점',
       '주구매중분류_4대 B/D', '주구매중분류_IT 게임기,S/W', '주구매중분류_KKD', '주구매중분류_L.B',
       '주구매중분류_L/C 아동복', '주구매중분류_L/C골프의류', '주구매중분류_L/C정장', '주구매중분류_MP3 外',
       '주구매중분류_N.B', '주구매중분류_N.B정장', '주구매중분류_N/B 아동복', '주구매중분류_N/B골프의류',
       '주구매중분류_NB 여화', '주구매중분류_TAKE OUT', '주구매중분류_takeout양과',
       '주구매중분류_가공선물세트', '주구매중분류_가공행사', '주구매중분류_가방', '주구매중분류_가스기기',
       '주구매중분류_갈비세트', '주구매중분류_건강가전', '주구매중분류_건강식품', '주구매중분류_건강식품(비타민)',
       '주구매중분류_건강식품(홍삼)', '주구매중분류_건강침대', '주구매중분류_건과', '주구매중분류_건생선',
       '주구매중분류_건어물류', '주구매중분류_계육', '주구매중분류_고정행사(골프)', '주구매중분류_고정행사(스포츠)',
       '주구매중분류_곡물', '주구매중분류_골프용품', '주구매중분류_구두단기행사', '주구매중분류_국산A/V',
       '주구매중분류_국산ACC', '주구매중분류_국산냉장고.세탁기', '주구매중분류_국산주방', '주구매중분류_굴비류',
       '주구매중분류_규격김치', '주구매중분류_규격젓갈', '주구매중분류_그라스', '주구매중분류_기능성침대',
       '주구매중분류_기초 화장품', '주구매중분류_기초A', '주구매중분류_기타',
       '주구매중분류_기타(가발,포장,담배,끽연구,사진,수선)', '주구매중분류_기타생선', '주구매중분류_김류',
       '주구매중분류_김치냉장고', '주구매중분류_넥타이(특정)', '주구매중분류_넥타이핀', '주구매중분류_농산가공',
       '주구매중분류_니  트', '주구매중분류_단기행사', '주구매중분류_단기행사(스포츠)', '주구매중분류_델리카',
       '주구매중분류_돈육', '주구매중분류_디자이너', '주구매중분류_디자이너부틱', '주구매중분류_디자이너캐릭터',
       '주구매중분류_디저트류', '주구매중분류_디지털카메라', '주구매중분류_떡', '주구매중분류_란제리',
       '주구매중분류_란제리행사', '주구매중분류_매트', '주구매중분류_면류', '주구매중분류_멸치류',
       '주구매중분류_명품기타', '주구매중분류_명품남성', '주구매중분류_명품멀티기타', '주구매중분류_명품보석',
       '주구매중분류_명품시계기타', '주구매중분류_명품잡화', '주구매중분류_모자(특정)', '주구매중분류_모피',
       '주구매중분류_밥류', '주구매중분류_벌크김치', '주구매중분류_벌크젓갈', '주구매중분류_보석',
       '주구매중분류_뷰티상품', '주구매중분류_비지니스군', '주구매중분류_산지통합', '주구매중분류_상품군미지정',
       '주구매중분류_색조 화장품', '주구매중분류_생선', '주구매중분류_서양델리', '주구매중분류_선식(가루류)',
       '주구매중분류_소품가구', '주구매중분류_수      저', '주구매중분류_수영복', '주구매중분류_수예소품',
       '주구매중분류_수입 아동복', '주구매중분류_수입단기행사', '주구매중분류_수입도자기', '주구매중분류_수입소형가전',
       '주구매중분류_수입식품', '주구매중분류_수입육', '주구매중분류_수입의류', '주구매중분류_수입주방',
       '주구매중분류_수입청소기 외', '주구매중분류_숙녀고정행사', '주구매중분류_스낵형 델리',
       '주구매중분류_스카프(특정)', '주구매중분류_스타킹(특정)', '주구매중분류_스트리트', '주구매중분류_스포츠의류',
       '주구매중분류_스포츠화', '주구매중분류_시니어', '주구매중분류_시티웨어', '주구매중분류_시티캐주얼',
       '주구매중분류_식탁', '주구매중분류_아웃도아', '주구매중분류_야채', '주구매중분류_양념육',
       '주구매중분류_양말(특정)', '주구매중분류_어덜트', '주구매중분류_엘리든직매입', '주구매중분류_영 캐릭터',
       '주구매중분류_영 트렌디', '주구매중분류_영캐주얼', '주구매중분류_영플라자(영캐주얼)',
       '주구매중분류_영플라자(이지)', '주구매중분류_영플라자(핸드백)', '주구매중분류_욕실용품',
       '주구매중분류_우/양산(특정)', '주구매중분류_우육', '주구매중분류_위생세제', '주구매중분류_유기농야채',
       '주구매중분류_유니섹스캐주얼', '주구매중분류_유아복', '주구매중분류_유제품', '주구매중분류_이지캐주얼',
       '주구매중분류_일반가공식품', '주구매중분류_일반침대', '주구매중분류_일반핸드백', '주구매중분류_일식델리',
       '주구매중분류_일용잡화', '주구매중분류_임대', '주구매중분류_장류', '주구매중분류_전기밥솥',
       '주구매중분류_종합가구', '주구매중분류_주류', '주구매중분류_주방잡화', '주구매중분류_직수입 골프의류',
       '주구매중분류_직수입핸드백', '주구매중분류_진캐주얼', '주구매중분류_차류', '주구매중분류_청과',
       '주구매중분류_초밥', '주구매중분류_캐릭터 남화', '주구매중분류_캐릭터 여화', '주구매중분류_캐릭터캐주얼',
       '주구매중분류_커리어', '주구매중분류_컨템포러리', '주구매중분류_컴퓨터', '주구매중분류_토들러',
       '주구매중분류_트래디셔널', '주구매중분류_트래디셔널Ⅰ', '주구매중분류_트래디셔널Ⅱ', '주구매중분류_트랜디',
       '주구매중분류_프레스티지', '주구매중분류_피혁', '주구매중분류_한과(세트행사)', '주구매중분류_한차',
       '주구매중분류_햄', '주구매중분류_향수', '주구매중분류_회', '주구매대분류_가공식품', '주구매대분류_가구',
       '주구매대분류_건강식품', '주구매대분류_골프', '주구매대분류_구두', '주구매대분류_기타',
       '주구매대분류_남성 캐주얼', '주구매대분류_남성 트랜디', '주구매대분류_남성정장', '주구매대분류_농산물',
       '주구매대분류_대형가전', '주구매대분류_디자이너', '주구매대분류_란제리/내의', '주구매대분류_명품',
       '주구매대분류_모피/피혁', '주구매대분류_생활잡화', '주구매대분류_섬유잡화', '주구매대분류_셔츠',
       '주구매대분류_소형가전', '주구매대분류_수산품', '주구매대분류_스포츠', '주구매대분류_시티웨어',
       '주구매대분류_식기', '주구매대분류_아동', '주구매대분류_액세서리', '주구매대분류_육류',
       '주구매대분류_일용잡화', '주구매대분류_젓갈/반찬', '주구매대분류_주류', '주구매대분류_주방가전',
       '주구매대분류_주방용품', '주구매대분류_차/커피', '주구매대분류_축산가공', '주구매대분류_침구/수예',
       '주구매대분류_캐주얼', '주구매대분류_커리어', '주구매대분류_통신/컴퓨터', '주구매대분류_트래디셔널',
       '주구매대분류_피혁잡화', '주구매대분류_화장품'], dtype=object)

In [ ]:
tmp = pd.DataFrame(
    enc.fit_transform(target_train[cols]).toarray(), # 넘파이 배열
    columns = enc.get_feature_names_out()
)
tmp.head()

,주구매지점_강남점,주구매지점_관악점,주구매지점_광주점,주구매지점_노원점,주구매지점_대구점,주구매지점_대전점,주구매지점_동래점,주구매지점_미아점,주구매지점_본 점,주구매지점_부산본점,...,주구매대분류_주방용품,주구매대분류_차/커피,주구매대분류_축산가공,주구매대분류_침구/수예,주구매대분류_캐주얼,주구매대분류_커리어,주구매대분류_통신/컴퓨터,주구매대분류_트래디셔널,주구매대분류_피혁잡화,주구매대분류_화장품
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
cols # 문자열이라 필요가 없어서 삭제

Index(['주구매지점', '주구매중분류', '주구매대분류'], dtype='object')

In [ ]:
data = pd.concat([target_train,tmp],axis = 1).drop(columns=cols)
data.head()

,고객번호,target,내점일수,구매주기,주말방문비율,주구매요일,봄구매비율,여름구매비율,가을구매비율,겨울구매비율,...,주구매대분류_주방용품,주구매대분류_차/커피,주구매대분류_축산가공,주구매대분류_침구/수예,주구매대분류_캐주얼,주구매대분류_커리어,주구매대분류_통신/컴퓨터,주구매대분류_트래디셔널,주구매대분류_피혁잡화,주구매대분류_화장품
0,10004,1,26,11.423077,0.617647,5,0.161765,0.397059,0.250000,0.191176,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10013,0,11,21.090909,0.117647,4,0.352941,0.235294,0.352941,0.058824,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10023,0,21,16.666667,0.348837,3,0.348837,0.162791,0.232558,0.255814,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10040,0,24,13.833333,0.121212,4,0.272727,0.151515,0.318182,0.257576,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10052,0,28,8.892857,0.333333,2,0.585586,0.243243,0.171171,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
data.info(verbose = True, null_counts = True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2554 entries, 0 to 2553
Data columns (total 257 columns):
 #    Column                         Non-Null Count  Dtype
---   ------                         --------------  -----
 0    고객번호                           2554 non-null   int64
 1    target                         2554 non-null   int64
 2    내점일수                           2554 non-null   int64
 3    구매주기                           2554 non-null   float64
 4    주말방문비율                         2554 non-null   float64
 5    주구매요일                          2554 non-null   int64
 6    봄구매비율                          2554 non-null   float64
 7    여름구매비율                         2554 non-null   float64
 8    가을구매비율                         2554 non-null   float64
 9    겨울구매비율                         2554 non-null   float64
 10   일평균구매건수                        2554 non-null   float64
 11   거래개월수                          2554 non-null   int64
 12   방문지점수                          2554 non-null   int64
 13   상품번호수                          2554 non-null   int64
 14   중분류수                           2554 non-null   int64
 15   대분류수                           2554 non-null   int64
 16   총구매액                           2554 non-null   int64
 17   구매건수                           2554 non-null   int64
 18   평균구매액                          2554 non-null   float64
 19   최대구매액                          2554 non-null   int64
 20   최소구매액                          2554 non-null   float64
 21   환불금액                           2554 non-null   int64
 22   환불건수                           2554 non-null   int64
 23   구매금액표준편차                       2554 non-null   float64
 24   주구매지점_강남점                      2554 non-null   float64
 25   주구매지점_관악점                      2554 non-null   float64
 26   주구매지점_광주점                      2554 non-null   float64
 27   주구매지점_노원점                      2554 non-null   float64
 28   주구매지점_대구점                      2554 non-null   float64
 29   주구매지점_대전점                      2554 non-null   float64
 30   주구매지점_동래점                      2554 non-null   float64
 31   주구매지점_미아점                      2554 non-null   float64
 32   주구매지점_본  점                     2554 non-null   float64
 33   주구매지점_부산본점                     2554 non-null   float64
 34   주구매지점_부평점                      2554 non-null   float64
 35   주구매지점_분당점                      2554 non-null   float64
 36   주구매지점_상인점                      2554 non-null   float64
 37   주구매지점_센텀시티점                    2554 non-null   float64
 38   주구매지점_안양점                      2554 non-null   float64
 39   주구매지점_영등포점                     2554 non-null   float64
 40   주구매지점_울산점                      2554 non-null   float64
 41   주구매지점_인천점                      2554 non-null   float64
 42   주구매지점_일산점                      2554 non-null   float64
 43   주구매지점_잠실점                      2554 non-null   float64
 44   주구매지점_전주점                      2554 non-null   float64
 45   주구매지점_창원점                      2554 non-null   float64
 46   주구매지점_청량리점                     2554 non-null   float64
 47   주구매지점_포항점                      2554 non-null   float64
 48   주구매중분류_4대 B/D                  2554 non-null   float64
 49   주구매중분류_IT 게임기,S/W              2554 non-null   float64
 50   주구매중분류_KKD                     2554 non-null   float64
 51   주구매중분류_L.B                     2554 non-null   float64
 52   주구매중분류_L/C 아동복                 2554 non-null   float64
 53   주구매중분류_L/C골프의류                 2554 non-null   float64
 54   주구매중분류_L/C정장                   2554 non-null   float64
 55   주구매중분류_MP3 外                   2554 non-null   float64
 56   주구매중분류_N.B                     2554 non-null   float64
 57   주구매중분류_N.B정장                   2554 non-null   float64
 58   주구매중분류_N/B 아동복                 2554 non-null   float64
 59   주구매중분류_N/B골프의류                 2554 non-null   float64
 60   주구매중분류_NB 여화                   2554 non-null   float64
 61   주구매중분류_TAKE OUT                2554 non-null   float64
 62   주구매중분류_takeout양과               2554 non-null   float64
 63   주구매중분류_가공선물세트                  2554 non-null   float64
 64   주구매중분류_가공행사                    2554 non-null   float64
 65   주구매중분류_가방                      2554 non-null   float64
 66   주구매중분류_가스기기                    2554 non-null   float64
 67   주구매중분류_갈비세트                    2554 non-null   float64
 68   주구매중분류_건강가전                    2554 non-null   float64
 69   주구매중분류_건강식품                    2554 non-null   float64
 70   주구매중분류_건강식품(비타민)               2554 non-null   float64
 71   주구매중분류_건강식품(홍삼)                2554 non-null   float64
 72   주구매중분류_건강침대                    2554 non-null   float64
 73   주구매중분류_건과                      2554 non-null   float64
 74   주구매중분류_건생선                     2554 non-null   float64
 75   주구매중분류_건어물류                    2554 non-null   float64
 76   주구매중분류_계육                      2554 non-null   float64
 77   주구매중분류_고정행사(골프)                2554 non-null   float64
 78   주구매중분류_고정행사(스포츠)               2554 non-null   float64
 79   주구매중분류_곡물                      2554 non-null   float64
 80   주구매중분류_골프용품                    2554 non-null   float64
 81   주구매중분류_구두단기행사                  2554 non-null   float64
 82   주구매중분류_국산A/V                   2554 non-null   float64
 83   주구매중분류_국산ACC                   2554 non-null   float64
 84   주구매중분류_국산냉장고.세탁기               2554 non-null   float64
 85   주구매중분류_국산주방                    2554 non-null   float64
 86   주구매중분류_굴비류                     2554 non-null   float64
 87   주구매중분류_규격김치                    2554 non-null   float64
 88   주구매중분류_규격젓갈                    2554 non-null   float64
 89   주구매중분류_그라스                     2554 non-null   float64
 90   주구매중분류_기능성침대                   2554 non-null   float64
 91   주구매중분류_기초 화장품                  2554 non-null   float64
 92   주구매중분류_기초A                     2554 non-null   float64
 93   주구매중분류_기타                      2554 non-null   float64
 94   주구매중분류_기타(가발,포장,담배,끽연구,사진,수선)  2554 non-null   float64
 95   주구매중분류_기타생선                    2554 non-null   float64
 96   주구매중분류_김류                      2554 non-null   float64
 97   주구매중분류_김치냉장고                   2554 non-null   float64
 98   주구매중분류_넥타이(특정)                 2554 non-null   float64
 99   주구매중분류_넥타이핀                    2554 non-null   float64
 100  주구매중분류_농산가공                    2554 non-null   float64
 101  주구매중분류_니  트                    2554 non-null   float64
 102  주구매중분류_단기행사                    2554 non-null   float64
 103  주구매중분류_단기행사(스포츠)               2554 non-null   float64
 104  주구매중분류_델리카                     2554 non-null   float64
 105  주구매중분류_돈육                      2554 non-null   float64
 106  주구매중분류_디자이너                    2554 non-null   float64
 107  주구매중분류_디자이너부틱                  2554 non-null   float64
 108  주구매중분류_디자이너캐릭터                 2554 non-null   float64
 109  주구매중분류_디저트류                    2554 non-null   float64
 110  주구매중분류_디지털카메라                  2554 non-null   float64
 111  주구매중분류_떡                       2554 non-null   float64
 112  주구매중분류_란제리                     2554 non-null   float64
 113  주구매중분류_란제리행사                   2554 non-null   float64
 114  주구매중분류_매트                      2554 non-null   float64
 115  주구매중분류_면류                      2554 non-null   float64
 116  주구매중분류_멸치류                     2554 non-null   float64
 117  주구매중분류_명품기타                    2554 non-null   float64
 118  주구매중분류_명품남성                    2554 non-null   float64
 119  주구매중분류_명품멀티기타                  2554 non-null   float64
 120  주구매중분류_명품보석                    2554 non-null   float64
 121  주구매중분류_명품시계기타                  2554 non-null   float64
 122  주구매중분류_명품잡화                    2554 non-null   float64
 123  주구매중분류_모자(특정)                  2554 non-null   float64
 124  주구매중분류_모피                      2554 non-null   float64
 125  주구매중분류_밥류                      2554 non-null   float64
 126  주구매중분류_벌크김치                    2554 non-null   float64
 127  주구매중분류_벌크젓갈                    2554 non-null   float64
 128  주구매중분류_보석                      2554 non-null   float64
 129  주구매중분류_뷰티상품                    2554 non-null   float64
 130  주구매중분류_비지니스군                   2554 non-null   float64
 131  주구매중분류_산지통합                    2554 non-null   float64
 132  주구매중분류_상품군미지정                  2554 non-null   float64
 133  주구매중분류_색조 화장품                  2554 non-null   float64
 134  주구매중분류_생선                      2554 non-null   float64
 135  주구매중분류_서양델리                    2554 non-null   float64
 136  주구매중분류_선식(가루류)                 2554 non-null   float64
 137  주구매중분류_소품가구                    2554 non-null   float64
 138  주구매중분류_수      저                2554 non-null   float64
 139  주구매중분류_수영복                     2554 non-null   float64
 140  주구매중분류_수예소품                    2554 non-null   float64
 141  주구매중분류_수입 아동복                  2554 non-null   float64
 142  주구매중분류_수입단기행사                  2554 non-null   float64
 143  주구매중분류_수입도자기                   2554 non-null   float64
 144  주구매중분류_수입소형가전                  2554 non-null   float64
 145  주구매중분류_수입식품                    2554 non-null   float64
 146  주구매중분류_수입육                     2554 non-null   float64
 147  주구매중분류_수입의류                    2554 non-null   float64
 148  주구매중분류_수입주방                    2554 non-null   float64
 149  주구매중분류_수입청소기 외                 2554 non-null   float64
 150  주구매중분류_숙녀고정행사                  2554 non-null   float64
 151  주구매중분류_스낵형 델리                  2554 non-null   float64
 152  주구매중분류_스카프(특정)                 2554 non-null   float64
 153  주구매중분류_스타킹(특정)                 2554 non-null   float64
 154  주구매중분류_스트리트                    2554 non-null   float64
 155  주구매중분류_스포츠의류                   2554 non-null   float64
 156  주구매중분류_스포츠화                    2554 non-null   float64
 157  주구매중분류_시니어                     2554 non-null   float64
 158  주구매중분류_시티웨어                    2554 non-null   float64
 159  주구매중분류_시티캐주얼                   2554 non-null   float64
 160  주구매중분류_식탁                      2554 non-null   float64
 161  주구매중분류_아웃도아                    2554 non-null   float64
 162  주구매중분류_야채                      2554 non-null   float64
 163  주구매중분류_양념육                     2554 non-null   float64
 164  주구매중분류_양말(특정)                  2554 non-null   float64
 165  주구매중분류_어덜트                     2554 non-null   float64
 166  주구매중분류_엘리든직매입                  2554 non-null   float64
 167  주구매중분류_영 캐릭터                   2554 non-null   float64
 168  주구매중분류_영 트렌디                   2554 non-null   float64
 169  주구매중분류_영캐주얼                    2554 non-null   float64
 170  주구매중분류_영플라자(영캐주얼)              2554 non-null   float64
 171  주구매중분류_영플라자(이지)                2554 non-null   float64
 172  주구매중분류_영플라자(핸드백)               2554 non-null   float64
 173  주구매중분류_욕실용품                    2554 non-null   float64
 174  주구매중분류_우/양산(특정)                2554 non-null   float64
 175  주구매중분류_우육                      2554 non-null   float64
 176  주구매중분류_위생세제                    2554 non-null   float64
 177  주구매중분류_유기농야채                   2554 non-null   float64
 178  주구매중분류_유니섹스캐주얼                 2554 non-null   float64
 179  주구매중분류_유아복                     2554 non-null   float64
 180  주구매중분류_유제품                     2554 non-null   float64
 181  주구매중분류_이지캐주얼                   2554 non-null   float64
 182  주구매중분류_일반가공식품                  2554 non-null   float64
 183  주구매중분류_일반침대                    2554 non-null   float64
 184  주구매중분류_일반핸드백                   2554 non-null   float64
 185  주구매중분류_일식델리                    2554 non-null   float64
 186  주구매중분류_일용잡화                    2554 non-null   float64
 187  주구매중분류_임대                      2554 non-null   float64
 188  주구매중분류_장류                      2554 non-null   float64
 189  주구매중분류_전기밥솥                    2554 non-null   float64
 190  주구매중분류_종합가구                    2554 non-null   float64
 191  주구매중분류_주류                      2554 non-null   float64
 192  주구매중분류_주방잡화                    2554 non-null   float64
 193  주구매중분류_직수입 골프의류                2554 non-null   float64
 194  주구매중분류_직수입핸드백                  2554 non-null   float64
 195  주구매중분류_진캐주얼                    2554 non-null   float64
 196  주구매중분류_차류                      2554 non-null   float64
 197  주구매중분류_청과                      2554 non-null   float64
 198  주구매중분류_초밥                      2554 non-null   float64
 199  주구매중분류_캐릭터 남화                  2554 non-null   float64
 200  주구매중분류_캐릭터 여화                  2554 non-null   float64
 201  주구매중분류_캐릭터캐주얼                  2554 non-null   float64
 202  주구매중분류_커리어                     2554 non-null   float64
 203  주구매중분류_컨템포러리                   2554 non-null   float64
 204  주구매중분류_컴퓨터                     2554 non-null   float64
 205  주구매중분류_토들러                     2554 non-null   float64
 206  주구매중분류_트래디셔널                   2554 non-null   float64
 207  주구매중분류_트래디셔널Ⅰ                  2554 non-null   float64
 208  주구매중분류_트래디셔널Ⅱ                  2554 non-null   float64
 209  주구매중분류_트랜디                     2554 non-null   float64
 210  주구매중분류_프레스티지                   2554 non-null   float64
 211  주구매중분류_피혁                      2554 non-null   float64
 212  주구매중분류_한과(세트행사)                2554 non-null   float64
 213  주구매중분류_한차                      2554 non-null   float64
 214  주구매중분류_햄                       2554 non-null   float64
 215  주구매중분류_향수                      2554 non-null   float64
 216  주구매중분류_회                       2554 non-null   float64
 217  주구매대분류_가공식품                    2554 non-null   float64
 218  주구매대분류_가구                      2554 non-null   float64
 219  주구매대분류_건강식품                    2554 non-null   float64
 220  주구매대분류_골프                      2554 non-null   float64
 221  주구매대분류_구두                      2554 non-null   float64
 222  주구매대분류_기타                      2554 non-null   float64
 223  주구매대분류_남성 캐주얼                  2554 non-null   float64
 224  주구매대분류_남성 트랜디                  2554 non-null   float64
 225  주구매대분류_남성정장                    2554 non-null   float64
 226  주구매대분류_농산물                     2554 non-null   float64
 227  주구매대분류_대형가전                    2554 non-null   float64
 228  주구매대분류_디자이너                    2554 non-null   float64
 229  주구매대분류_란제리/내의                  2554 non-null   float64
 230  주구매대분류_명품                      2554 non-null   float64
 231  주구매대분류_모피/피혁                   2554 non-null   float64
 232  주구매대분류_생활잡화                    2554 non-null   float64
 233  주구매대분류_섬유잡화                    2554 non-null   float64
 234  주구매대분류_셔츠                      2554 non-null   float64
 235  주구매대분류_소형가전                    2554 non-null   float64
 236  주구매대분류_수산품                     2554 non-null   float64
 237  주구매대분류_스포츠                     2554 non-null   float64
 238  주구매대분류_시티웨어                    2554 non-null   float64
 239  주구매대분류_식기                      2554 non-null   float64
 240  주구매대분류_아동                      2554 non-null   float64
 241  주구매대분류_액세서리                    2554 non-null   float64
 242  주구매대분류_육류                      2554 non-null   float64
 243  주구매대분류_일용잡화                    2554 non-null   float64
 244  주구매대분류_젓갈/반찬                   2554 non-null   float64
 245  주구매대분류_주류                      2554 non-null   float64
 246  주구매대분류_주방가전                    2554 non-null   float64
 247  주구매대분류_주방용품                    2554 non-null   float64
 248  주구매대분류_차/커피                    2554 non-null   float64
 249  주구매대분류_축산가공                    2554 non-null   float64
 250  주구매대분류_침구/수예                   2554 non-null   float64
 251  주구매대분류_캐주얼                     2554 non-null   float64
 252  주구매대분류_커리어                     2554 non-null   float64
 253  주구매대분류_통신/컴퓨터                  2554 non-null   float64
 254  주구매대분류_트래디셔널                   2554 non-null   float64
 255  주구매대분류_피혁잡화                    2554 non-null   float64
 256  주구매대분류_화장품                     2554 non-null   float64
dtypes: float64(243), int64(14)
memory usage: 5.0 MB

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: null_counts is deprecated. Use show_counts instead
  """Entry point for launching an IPython kernel.

### 특성 데이터와 정답값 분리

In [ ]:
x_data = data.iloc[:,2:] # 내점일수부터 필요하기 때문에 슬라이싱
y_data = data["target"]

x_data.shape, y_data.shape

((2554, 255), (2554,))

### Feature Scaling

In [ ]:
scaler = MinMaxScaler()

x_data = scaler.fit_transform(x_data)
x_data

array([[0.08802817, 0.06881372, 0.61764706, ..., 0.        , 0.        ,
        0.        ],
       [0.03521127, 0.12705367, 0.11764706, ..., 0.        , 0.        ,
        0.        ],
       [0.07042254, 0.10040161, 0.34883721, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.00704225, 0.11044177, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.02112676, 0.18244406, 0.54545455, ..., 0.        , 0.        ,
        0.        ],
       [0.01408451, 0.21445783, 0.04761905, ..., 0.        , 0.        ,
        0.        ]])

### 학습데이터 검증데이터 분리

In [ ]:
x_train, x_valid, y_train, y_valid = train_test_split(x_data, y_data, test_size=0.2, random_state=SEED)

x_train.shape, x_valid.shape, y_train.shape, y_valid.shape

((2043, 255), (511, 255), (2043,), (511,))

## 학습하기

In [ ]:
model = LogisticRegression(random_state=SEED)

model.fit(x_train,y_train)

LogisticRegression(random_state=42)

## 검증셋 평가하기

In [ ]:
pred = model.predict(x_valid)
accuracy_score(y_valid,pred)

0.6868884540117417

-------------------------------------------------------------------------------------------------

In [ ]:
target_train.select_dtypes("object").nunique()

주구매지점      24
주구매중분류    169
주구매대분류     40
dtype: int64

In [ ]:
cols = ["주구매지점","주구매대분류"]
enc = OneHotEncoder()
tmp = pd.DataFrame(
    enc.fit_transform(target_train[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
tmp.head()

,주구매지점_강남점,주구매지점_관악점,주구매지점_광주점,주구매지점_노원점,주구매지점_대구점,주구매지점_대전점,주구매지점_동래점,주구매지점_미아점,주구매지점_본 점,주구매지점_부산본점,...,주구매대분류_주방용품,주구매대분류_차/커피,주구매대분류_축산가공,주구매대분류_침구/수예,주구매대분류_캐주얼,주구매대분류_커리어,주구매대분류_통신/컴퓨터,주구매대분류_트래디셔널,주구매대분류_피혁잡화,주구매대분류_화장품
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
data = pd.concat([target_train,tmp],axis = 1).drop(columns=cols)
data.head()

,고객번호,target,내점일수,구매주기,주말방문비율,주구매요일,봄구매비율,여름구매비율,가을구매비율,겨울구매비율,...,주구매대분류_주방용품,주구매대분류_차/커피,주구매대분류_축산가공,주구매대분류_침구/수예,주구매대분류_캐주얼,주구매대분류_커리어,주구매대분류_통신/컴퓨터,주구매대분류_트래디셔널,주구매대분류_피혁잡화,주구매대분류_화장품
0,10004,1,26,11.423077,0.617647,5,0.161765,0.397059,0.250000,0.191176,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,10013,0,11,21.090909,0.117647,4,0.352941,0.235294,0.352941,0.058824,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,10023,0,21,16.666667,0.348837,3,0.348837,0.162791,0.232558,0.255814,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,10040,0,24,13.833333,0.121212,4,0.272727,0.151515,0.318182,0.257576,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,10052,0,28,8.892857,0.333333,2,0.585586,0.243243,0.171171,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
tmp = target_train["주구매중분류"].value_counts().reset_index() # 카운트 인코딩
tmp

          index  주구매중분류
0        상품군미지정    1028
1        기초 화장품     203
2        디자이너부틱     144
3          농산가공      63
4          니  트      60
..          ...     ...
164      직수입핸드백       1
165          보석       1
166  영플라자(영캐주얼)       1
167          향수       1
168          피혁       1

[169 rows x 2 columns]

In [ ]:
tmp.columns = ["주구매중분류","주구매중분류_cnt"]
tmp.head()

   주구매중분류  주구매중분류_cnt
0  상품군미지정        1028
1  기초 화장품         203
2  디자이너부틱         144
3    농산가공          63
4    니  트          60

In [ ]:
data["주구매중분류"] # merge!

0        상품군미지정
1         N.B정장
2       N/B골프의류
3           어덜트
4          시티웨어
         ...
2549     상품군미지정
2550       농산가공
2551        어덜트
2552         건과
2553     상품군미지정
Name: 주구매중분류, Length: 2554, dtype: object

In [ ]:
data = data.merge(tmp,how="left",on="주구매중분류").drop(columns=["주구매중분류"])
data.head()

,고객번호,target,내점일수,구매주기,주말방문비율,주구매요일,봄구매비율,여름구매비율,가을구매비율,겨울구매비율,...,주구매대분류_차/커피,주구매대분류_축산가공,주구매대분류_침구/수예,주구매대분류_캐주얼,주구매대분류_커리어,주구매대분류_통신/컴퓨터,주구매대분류_트래디셔널,주구매대분류_피혁잡화,주구매대분류_화장품,주구매중분류_cnt
0,10004,1,26,11.423077,0.617647,5,0.161765,0.397059,0.250000,0.191176,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1028
1,10013,0,11,21.090909,0.117647,4,0.352941,0.235294,0.352941,0.058824,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19
2,10023,0,21,16.666667,0.348837,3,0.348837,0.162791,0.232558,0.255814,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25
3,10040,0,24,13.833333,0.121212,4,0.272727,0.151515,0.318182,0.257576,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21
4,10052,0,28,8.892857,0.333333,2,0.585586,0.243243,0.171171,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,47

In [ ]:
x_data = data.iloc[:,2:]
y_data = data["target"]
x_data.shape, y_data.shape

((2554, 87), (2554,))

In [ ]:
scaler = MinMaxScaler()
x_data = scaler.fit_transform(x_data)
x_data

array([[0.08802817, 0.06881372, 0.61764706, ..., 0.        , 0.        ,
        1.        ],
       [0.03521127, 0.12705367, 0.11764706, ..., 0.        , 0.        ,
        0.01752678],
       [0.07042254, 0.10040161, 0.34883721, ..., 0.        , 0.        ,
        0.02336904],
       ...,
       [0.00704225, 0.11044177, 0.33333333, ..., 0.        , 0.        ,
        0.0194742 ],
       [0.02112676, 0.18244406, 0.54545455, ..., 0.        , 0.        ,
        0.01071081],
       [0.01408451, 0.21445783, 0.04761905, ..., 0.        , 0.        ,
        1.        ]])

In [ ]:
x_train, x_valid, y_train, y_valid = train_test_split(x_data, y_data, test_size=0.2, random_state=SEED)

x_train.shape, x_valid.shape, y_train.shape, y_valid.shape # feature가 많이 줄어든것을 확인 할 수 있다. (feature가 너무 많으면 차원의 저주가 발생할 수 있다.)

((2043, 87), (511, 87), (2043,), (511,))

In [ ]:
model = LogisticRegression(random_state=SEED)

model.fit(x_train,y_train)

LogisticRegression(random_state=42)

In [ ]:
pred = model.predict(x_valid)
accuracy_score(y_valid,pred)

0.6712328767123288